import type { PartDefinition } from '../part-registry'

export const VEHICLE_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'vehicle.body_shell',
    family: 'vehicle',
    kind: 'body_shell',
    semanticRole: 'vehicle_body',
    aliases: ['body', 'car_body', 'vehicle_body', 'main_body', 'chassis', '车身', '底盘'],
    required: true,
    description: 'Main vehicle body shell.',
    params: {
      length: { type: 'number', min: 2, max: 8, default: 4.4 },
      width: { type: 'number', min: 1, max: 3, default: 1.8 },
      height: { type: 'number', min: 0.7, max: 3, default: 1.35 },
      primaryColor: { type: 'color', default: '#cc0000' },
      vehicleStyle: {
        type: 'enum',
        values: ['sedan', 'suv', 'sports', 'truck', 'van'],
        default: 'sedan',
      },
      cornerRadius: { type: 'number', min: 0, max: 0.8 },
    },
  },
  {
    id: 'vehicle.wheel_set',
    family: 'vehicle',
    kind: 'wheel_set',
    semanticRole: 'vehicle_tire',
    aliases: ['wheel', 'wheels', 'tire', 'tyre', 'vehicle_wheels', '车轮', '轮胎'],
    required: true,
    attachTo: 'body_shell',
    layoutRole: 'lower_four_corners',
    description: 'Vehicle wheel/tire set.',
    params: {
      count: { type: 'integer', values: [2, 4, 6], default: 4 },
      radius: { type: 'number', min: 0.15, max: 0.8, default: 0.38 },
      width: { type: 'number', min: 0.08, max: 0.5, default: 0.22 },
      wheelRadius: { type: 'number', min: 0.15, max: 0.8 },
      wheelWidth: { type: 'number', min: 0.08, max: 0.5 },
      hubColor: { type: 'color', default: '#d8d8d8' },
    },
  },
  {
    id: 'vehicle.window_strip',
    family: 'vehicle',
    kind: 'window_strip',
    semanticRole: 'vehicle_window',
    aliases: ['window', 'windows', 'vehicle_windows', 'glass', 'windshield', '车窗', '玻璃'],
    required: true,
    attachTo: 'body_shell',
    layoutRole: 'cabin_band',
    description: 'Vehicle glasshouse/window band.',
    params: {
      height: { type: 'number', min: 0.12, max: 1.2, default: 0.42 },
      tint: { type: 'color', default: '#77aaff' },
      opacity: { type: 'number', min: 0.1, max: 1, default: 0.68 },
      variant: { type: 'enum', values: ['vehicle_glasshouse'], default: 'vehicle_glasshouse' },
    },
  },
  {
    id: 'vehicle.light_pair',
    family: 'vehicle',
    kind: 'light_pair',
    semanticRole: 'headlight',
    aliases: ['light', 'lights', 'headlight', 'headlights', '车灯', '大灯'],
    required: true,
    attachTo: 'body_shell',
    layoutRole: 'front_face',
    description: 'Front light pair.',
    params: {
      size: { type: 'number', min: 0.04, max: 0.4, default: 0.12 },
      color: { type: 'color', default: '#f8fafc' },
    },
  },
  {
    id: 'vehicle.bar_pair',
    family: 'vehicle',
    kind: 'bar_pair',
    aliases: ['bumper', 'bumpers', 'front_bumper', 'rear_bumper', '保险杠'],
    required: true,
    attachTo: 'body_shell',
    layoutRole: 'front_rear_bars',
    description: 'Front and rear bumper bars.',
    params: {
      height: { type: 'number', min: 0.04, max: 0.35, default: 0.12 },
      thickness: { type: 'number', min: 0.02, max: 0.2, default: 0.06 },
    },
  },
  {
    id: 'vehicle.seam_ring',
    family: 'vehicle',
    kind: 'seam_ring',
    aliases: ['seam', 'panel_seam', 'trim', '腰线', '缝线'],
    attachTo: 'body_shell',
    layoutRole: 'body_detail',
    description: 'Body seam or trim detail.',
    params: {
      radius: { type: 'number', min: 0.04, max: 0.5, default: 0.18 },
    },
  },
]

export const DESK_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'desk.desk_top',
    family: 'desk',
    kind: 'desk_top',
    semanticRole: 'furniture_body',
    aliases: ['desk', 'table', 'desktop', 'tabletop', 'worktop', 'office_desk', 'writing_desk'],
    required: true,
    description: 'Desk or table top slab.',
    params: {
      length: { type: 'number', min: 0.35, max: 4, default: 1.2 },
      width: { type: 'number', min: 0.2, max: 2, default: 0.6 },
      height: { type: 'number', min: 0.02, max: 0.18, default: 0.055 },
      primaryColor: { type: 'color', default: '#b7794b' },
    },
  },
  {
    id: 'desk.leg_set',
    family: 'desk',
    kind: 'leg_set',
    semanticRole: 'support_leg',
    aliases: ['legs', 'table_legs', 'desk_legs', 'support_legs', 'feet', 'supports'],
    required: true,
    attachTo: 'desk_top',
    layoutRole: 'four_corners_under_top',
    description: 'Four desk/table legs with rear stretcher.',
    params: {
      length: { type: 'number', min: 0.25, max: 4, default: 1.08 },
      width: { type: 'number', min: 0.15, max: 2, default: 0.5 },
      height: { type: 'number', min: 0.12, max: 1.4, default: 0.7 },
      radius: { type: 'number', min: 0.008, max: 0.09, default: 0.025 },
      metalColor: { type: 'color', default: '#9ca3af' },
    },
  },
  {
    id: 'desk.drawer_stack',
    family: 'desk',
    kind: 'drawer_stack',
    semanticRole: 'drawer_stack',
    aliases: ['drawer', 'drawers', 'drawer_stack', 'cabinet_drawers', 'side_drawers'],
    attachTo: 'desk_top',
    layoutRole: 'side_under_top',
    description: 'Optional drawer cabinet under one side of a desk.',
    params: {
      length: { type: 'number', min: 0.14, max: 1.2, default: 0.34 },
      width: { type: 'number', min: 0.12, max: 1, default: 0.44 },
      height: { type: 'number', min: 0.16, max: 1.1, default: 0.52 },
      count: { type: 'integer', min: 1, max: 6, default: 3 },
      primaryColor: { type: 'color', default: '#a16207' },
      secondaryColor: { type: 'color', default: '#c08457' },
    },
  },
]

export const FAN_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'fan.circular_base',
    family: 'fan',
    kind: 'circular_base',
    semanticRole: 'fan_base',
    aliases: ['base', 'round_base', 'pedestal_base', 'fan_base'],
    required: true,
    description: 'Weighted circular base for a standing or pedestal fan.',
    params: {
      radius: { type: 'number', min: 0.05, max: 2, default: 0.28 },
      height: { type: 'number', min: 0.01, max: 0.4, default: 0.08 },
      primaryColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'fan.vertical_pole',
    family: 'fan',
    kind: 'vertical_pole',
    semanticRole: 'fan_pole',
    aliases: ['pole', 'stand', 'vertical_pole', 'pedestal_pole'],
    required: true,
    attachTo: 'circular_base',
    layoutRole: 'vertical_support',
    description: 'Vertical support pole for a standing fan.',
    params: {
      radius: { type: 'number', min: 0.005, max: 0.15, default: 0.025 },
      height: { type: 'number', min: 0.05, max: 4, default: 1.05 },
      metalColor: { type: 'color', default: '#64748b' },
    },
  },
  {
    id: 'fan.support_bracket',
    family: 'fan',
    kind: 'support_bracket',
    semanticRole: 'fan_yoke',
    aliases: ['support_bracket', 'yoke', 'tilt_bracket', 'neck_bracket'],
    attachTo: 'vertical_pole',
    layoutRole: 'head_support',
    description: 'Yoke or bracket between pole and fan head.',
    params: {
      width: { type: 'number', min: 0.04, max: 1, default: 0.24 },
      height: { type: 'number', min: 0.03, max: 0.8, default: 0.16 },
      depth: { type: 'number', min: 0.01, max: 0.3, default: 0.045 },
      metalColor: { type: 'color', default: '#64748b' },
    },
  },
  {
    id: 'fan.motor_housing',
    family: 'fan',
    kind: 'motor_housing',
    semanticRole: 'motor_housing',
    aliases: ['motor', 'motor_housing', 'rear_motor', 'fan_head'],
    required: true,
    attachTo: 'support_bracket',
    layoutRole: 'fan_head_center',
    description: 'Rear motor housing at the center of the fan head.',
    params: {
      radius: { type: 'number', min: 0.03, max: 0.5, default: 0.11 },
      depth: { type: 'number', min: 0.03, max: 0.8, default: 0.16 },
      primaryColor: { type: 'color', default: '#30343b' },
    },
  },
  {
    id: 'fan.fan_blade',
    family: 'fan',
    kind: 'fan_blade',
    semanticRole: 'fan_blade',
    aliases: ['fan_blade', 'blade', 'editable_blade', 'independent_blade'],
    required: true,
    attachTo: 'motor_housing',
    layoutRole: 'radial_blade_array',
    description: 'Independent editable fan blade array; each generated blade has its own part id.',
    params: {
      count: { type: 'integer', min: 1, max: 16, default: 1 },
      length: { type: 'number', min: 0.04, max: 1.2, default: 0.24 },
      width: { type: 'number', min: 0.012, max: 0.55 },
      thickness: { type: 'number', min: 0.003, max: 0.08, default: 0.018 },
      pitch: { type: 'number', min: -0.8, max: 0.8, default: 0.24 },
      bladeSweep: { type: 'number', min: -0.55, max: 0.55 },
      primaryColor: { type: 'color', default: '#8ec5ff' },
      includeHub: { type: 'boolean', default: true },
    },
  },
  {
    id: 'fan.radial_blades',
    family: 'fan',
    kind: 'radial_blades',
    semanticRole: 'fan_blade',
    aliases: ['fan_blades', 'radial_blades', 'blade_set', 'impeller'],
    attachTo: 'motor_housing',
    layoutRole: 'radial_blade_set',
    description: 'Composite radial fan blade set kept for compatibility with older profiles.',
    params: {
      count: { type: 'integer', min: 2, max: 8, default: 3 },
      bladeRadius: { type: 'number', min: 0.05, max: 1.4, default: 0.28 },
      bladeWidth: { type: 'number', min: 0.01, max: 0.8 },
      bladePitch: { type: 'number', min: -0.65, max: 0.65, default: 0.24 },
      primaryColor: { type: 'color', default: '#8ec5ff' },
    },
  },
  {
    id: 'fan.protective_grill',
    family: 'fan',
    kind: 'protective_grill',
    semanticRole: 'protective_grill',
    aliases: ['grill', 'grille', 'cage', 'guard', 'protective_grill'],
    attachTo: 'motor_housing',
    layoutRole: 'front_guard',
    description: 'Protective cage with rings and spokes around the fan blades.',
    params: {
      radius: { type: 'number', min: 0.08, max: 2, default: 0.36 },
      depth: { type: 'number', min: 0.005, max: 0.6, default: 0.12 },
      detailLevel: { type: 'enum', values: ['low', 'medium', 'high'], default: 'medium' },
      ringCount: { type: 'integer', min: 1, max: 8, default: 4 },
      spokeCount: { type: 'integer', min: 6, max: 36, default: 18 },
      wireRadius: { type: 'number', min: 0.002, max: 0.05 },
      metalColor: { type: 'color', default: '#d1d5db' },
    },
  },
  {
    id: 'fan.control_knob',
    family: 'fan',
    kind: 'control_knob',
    semanticRole: 'control_knob',
    aliases: ['knob', 'control_knob', 'speed_knob'],
    attachTo: 'vertical_pole',
    layoutRole: 'control_detail',
    description: 'Small speed or oscillation control knob.',
    params: {
      radius: { type: 'number', min: 0.01, max: 0.2, default: 0.045 },
      depth: { type: 'number', min: 0.004, max: 0.12, default: 0.025 },
      accentColor: { type: 'color', default: '#ef4444' },
    },
  },
]

export const AIRCRAFT_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'aircraft.aircraft_fuselage',
    family: 'aircraft',
    kind: 'aircraft_fuselage',
    semanticRole: 'aircraft_fuselage',
    aliases: [
      'aircraft',
      'airplane',
      'airliner',
      'plane',
      'jet',
      'fuselage',
      'fuselage_body',
      'streamlined_body',
      'airplane_body',
      'aircraft_body',
    ],
    required: true,
    description: 'Streamlined aircraft fuselage with conformal windows and livery stripes.',
    params: {
      length: { type: 'number', min: 0.4, max: 20 },
      width: { type: 'number', min: 0.05, max: 3 },
      height: { type: 'number', min: 0.04, max: 3 },
      count: { type: 'integer', min: 6, max: 40 },
      primaryColor: { type: 'color' },
      accentColor: { type: 'color' },
      noseRoundness: { type: 'number', min: 0, max: 1 },
      tailTaper: { type: 'number', min: 0, max: 1 },
      roofArc: { type: 'number', min: 0, max: 0.4 },
    },
  },
  {
    id: 'aircraft.aircraft_wing',
    family: 'aircraft',
    kind: 'aircraft_wing',
    semanticRole: 'aircraft_wing',
    aliases: [
      'wing',
      'wings',
      'main_wing',
      'main_wings',
      'left_wing',
      'right_wing',
      'swept_wing',
      'airfoil_blade',
      'lofted_panel',
    ],
    required: true,
    attachTo: 'aircraft_fuselage',
    layoutRole: 'main_low_wings',
    description: 'Symmetric swept aircraft wing pair.',
    params: {
      length: { type: 'number', min: 0.2, max: 16 },
      width: { type: 'number', min: 0.04, max: 1.2 },
      thickness: { type: 'number', min: 0.004, max: 0.08 },
      bladeSweep: { type: 'number', min: -0.5, max: 0.5 },
      verticalCurve: { type: 'number', min: -0.25, max: 0.25 },
      color: { type: 'color' },
    },
  },
  {
    id: 'aircraft.aircraft_engine',
    family: 'aircraft',
    kind: 'aircraft_engine',
    semanticRole: 'engine_nacelle',
    aliases: [
      'engine',
      'engines',
      'jet_engine',
      'jet_engines',
      'turbofan',
      'turbofans',
      'nacelle',
      'nacelles',
      'engine_nacelle',
      'engine_nacelles',
    ],
    required: true,
    attachTo: 'aircraft_wing',
    layoutRole: 'underwing_pair',
    description: 'Aircraft turbofan nacelles with intake lips and fan disks.',
    params: {
      count: { type: 'integer', min: 1, max: 4 },
      radius: { type: 'number', min: 0.018, max: 0.36 },
      length: { type: 'number', min: 0.05, max: 1.25 },
      width: { type: 'number', min: 0.06, max: 4 },
      color: { type: 'color' },
    },
  },
  {
    id: 'aircraft.aircraft_vertical_stabilizer',
    family: 'aircraft',
    kind: 'aircraft_vertical_stabilizer',
    semanticRole: 'vertical_stabilizer',
    aliases: [
      'vertical_stabilizer',
      'vertical_stabiliser',
      'vertical_tail',
      'vertical_fin',
      'tail_fin',
      'rudder',
    ],
    required: true,
    attachTo: 'aircraft_fuselage',
    layoutRole: 'tail_fin',
    description: 'Swept vertical tail fin.',
    params: {
      length: { type: 'number', min: 0.04, max: 1.5 },
      height: { type: 'number', min: 0.04, max: 1.4 },
      width: { type: 'number', min: 0.004, max: 0.16 },
      color: { type: 'color' },
    },
  },
  {
    id: 'aircraft.aircraft_horizontal_stabilizer',
    family: 'aircraft',
    kind: 'aircraft_horizontal_stabilizer',
    semanticRole: 'horizontal_stabilizer',
    aliases: [
      'horizontal_stabilizer',
      'horizontal_stabiliser',
      'horizontal_tail',
      'tailplane',
      't_tail',
      't_tail_stabilizer',
    ],
    required: true,
    attachTo: 'aircraft_vertical_stabilizer',
    layoutRole: 't_tail',
    description: 'Horizontal tail stabilizer pair.',
    params: {
      length: { type: 'number', min: 0.08, max: 2.5 },
      width: { type: 'number', min: 0.03, max: 0.8 },
      thickness: { type: 'number', min: 0.003, max: 0.08 },
      verticalCurve: { type: 'number', min: -0.25, max: 0.25 },
      color: { type: 'color' },
    },
  },
  {
    id: 'aircraft.aircraft_landing_gear',
    family: 'aircraft',
    kind: 'aircraft_landing_gear',
    semanticRole: 'landing_gear_wheel',
    aliases: [
      'landing_gear',
      'landing_wheel',
      'landing_wheels',
      'landing_gear_wheel',
      'nose_gear',
      'main_gear',
      'wheel_set',
      'wheels',
    ],
    required: true,
    attachTo: 'aircraft_fuselage',
    layoutRole: 'tricycle_gear',
    description: 'Tricycle landing gear wheels and struts.',
    params: {
      length: { type: 'number', min: 0.06, max: 2.5 },
      width: { type: 'number', min: 0.04, max: 1.4 },
      radius: { type: 'number', min: 0.012, max: 0.2 },
      wheelRadius: { type: 'number', min: 0.012, max: 0.2 },
      color: { type: 'color' },
    },
  },
]

export const GENERIC_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'generic.generic_body',
    family: 'generic',
    kind: 'generic_body',
    semanticRole: 'main_body',
    aliases: [
      'body',
      'main_body',
      'housing',
      'shell',
      'cabinet_body',
      'equipment_body',
      'building_body',
      'furniture_body',
    ],
    required: true,
    description: 'Generic primary body/housing for unknown long-tail objects.',
    params: {
      length: { type: 'number', min: 0.08, max: 8, default: 1 },
      width: { type: 'number', min: 0.05, max: 5, default: 0.65 },
      height: { type: 'number', min: 0.05, max: 5, default: 0.8 },
      primaryColor: { type: 'color', default: '#8b9aae' },
      cornerRadius: { type: 'number', min: 0, max: 0.5 },
    },
  },
  {
    id: 'generic.generic_base',
    family: 'generic',
    kind: 'generic_base',
    semanticRole: 'support_base',
    aliases: ['base', 'support_base', 'platform', 'cup_platform', 'plinth', 'skid'],
    required: true,
    description: 'Generic base, plinth, or platform.',
    params: {
      length: { type: 'number', min: 0.08, max: 8, default: 1.08 },
      width: { type: 'number', min: 0.05, max: 5, default: 0.72 },
      height: { type: 'number', min: 0.01, max: 0.8, default: 0.08 },
      thickness: { type: 'number', min: 0.01, max: 0.8 },
      darkColor: { type: 'color', default: '#1f2937' },
    },
  },
  {
    id: 'generic.generic_panel',
    family: 'generic',
    kind: 'generic_panel',
    semanticRole: 'panel',
    aliases: ['panel', 'front_panel', 'side_panel', 'access_panel', 'roof'],
    description: 'Generic flat panel or cover.',
    params: {
      length: { type: 'number', min: 0.02, max: 4, default: 0.3 },
      height: { type: 'number', min: 0.02, max: 3, default: 0.22 },
      thickness: { type: 'number', min: 0.002, max: 0.4, default: 0.025 },
      color: { type: 'color', default: '#94a3b8' },
    },
  },
  {
    id: 'generic.generic_handle',
    family: 'generic',
    kind: 'generic_handle',
    semanticRole: 'handle',
    aliases: ['handle', 'pull_handle', 'door_handle'],
    description: 'Generic small handle or pull.',
    params: {
      length: { type: 'number', min: 0.03, max: 2, default: 0.22 },
      radius: { type: 'number', min: 0.004, max: 0.12, default: 0.018 },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'generic.generic_spout',
    family: 'generic',
    kind: 'generic_spout',
    semanticRole: 'spout',
    aliases: ['spout', 'nozzle_spout', 'coffee_spout', 'dispense_spout'],
    description: 'Generic dispensing spout or short nozzle.',
    params: {
      length: { type: 'number', min: 0.02, max: 1.2, default: 0.2 },
      radius: { type: 'number', min: 0.004, max: 0.2, default: 0.035 },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'generic.generic_control_panel',
    family: 'generic',
    kind: 'generic_control_panel',
    semanticRole: 'control_detail',
    aliases: ['control_panel', 'control_detail', 'buttons', 'button_panel'],
    description: 'Generic control/button panel.',
    params: {
      length: { type: 'number', min: 0.02, max: 4, default: 0.3 },
      height: { type: 'number', min: 0.02, max: 3, default: 0.22 },
      thickness: { type: 'number', min: 0.002, max: 0.4, default: 0.025 },
      accentColor: { type: 'color', default: '#38bdf8' },
    },
  },
  {
    id: 'generic.generic_display',
    family: 'generic',
    kind: 'generic_display',
    semanticRole: 'display',
    aliases: ['display', 'screen', 'readout'],
    description: 'Generic dark display or screen panel.',
    params: {
      length: { type: 'number', min: 0.02, max: 4, default: 0.28 },
      height: { type: 'number', min: 0.02, max: 3, default: 0.16 },
      thickness: { type: 'number', min: 0.002, max: 0.4, default: 0.025 },
      color: { type: 'color', default: '#0f172a' },
    },
  },
  {
    id: 'generic.generic_foot_set',
    family: 'generic',
    kind: 'generic_foot_set',
    semanticRole: 'support_foot',
    aliases: ['feet', 'foot_set', 'support_feet'],
    description: 'Generic four-foot support set.',
    params: {
      radius: { type: 'number', min: 0.006, max: 0.18, default: 0.035 },
      height: { type: 'number', min: 0.02, max: 0.8, default: 0.08 },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'generic.generic_opening',
    family: 'generic',
    kind: 'generic_opening',
    semanticRole: 'opening',
    aliases: ['opening', 'door_opening', 'window_opening'],
    description: 'Generic dark door/window/opening panel.',
    params: {
      length: { type: 'number', min: 0.02, max: 4, default: 0.24 },
      height: { type: 'number', min: 0.02, max: 3, default: 0.28 },
      thickness: { type: 'number', min: 0.002, max: 0.4, default: 0.025 },
      color: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'generic.generic_detail_accent',
    family: 'generic',
    kind: 'generic_detail_accent',
    semanticRole: 'detail_accent',
    aliases: ['detail', 'detail_accent', 'accent', 'trim'],
    description: 'Generic small accent/detail marker.',
    params: {
      length: { type: 'number', min: 0.02, max: 4, default: 0.24 },
      height: { type: 'number', min: 0.02, max: 3, default: 0.14 },
      thickness: { type: 'number', min: 0.002, max: 0.4, default: 0.025 },
      accentColor: { type: 'color', default: '#38bdf8' },
    },
  },
  {
    id: 'generic.hemisphere',
    family: 'generic',
    kind: 'hemisphere',
    semanticRole: 'hemisphere',
    aliases: [
      'hemisphere',
      'half_sphere',
      'half-sphere',
      'semi_sphere',
      'semi-sphere',
      'dome',
      'half_dome',
      'half-dome',
      '\u534a\u7403',
      '\u534a\u7403\u4f53',
      '\u534a\u5706\u7403',
      '\u534a\u5706\u5f62\u7403',
    ],
    description: 'Closed half-sphere/dome primitive with editable footprint diameter and height.',
    params: {
      radius: { type: 'number', min: 0.01, max: 10, default: 0.5 },
      diameter: { type: 'number', min: 0.02, max: 20, default: 1 },
      length: { type: 'number', min: 0.02, max: 20 },
      width: { type: 'number', min: 0.02, max: 20 },
      height: { type: 'number', min: 0.01, max: 10 },
      primaryColor: { type: 'color', default: '#94a3b8' },
      widthSegments: { type: 'integer', min: 8, max: 64, default: 32 },
      heightSegments: { type: 'integer', min: 4, max: 32, default: 16 },
    },
  },
  {
    id: 'generic.manway_lid',
    family: 'generic',
    kind: 'manway_lid',
    semanticRole: 'manway_lid',
    aliases: ['manway_lid', 'manway_cover', 'access_lid', 'hatch_cover'],
    description: 'Flat bolted manway or access cover for process vessels.',
    params: {
      radius: { type: 'number', min: 0.04, max: 1, default: 0.18 },
      thickness: { type: 'number', min: 0.006, max: 0.25, default: 0.035 },
      boltCount: { type: 'integer', min: 0, max: 24, default: 8 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'y' },
      metalColor: { type: 'color', default: '#cbd5e1' },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'generic.sanitary_nozzle',
    family: 'generic',
    kind: 'sanitary_nozzle',
    semanticRole: 'sanitary_nozzle',
    aliases: ['sanitary_nozzle', 'tri_clamp_nozzle', 'hygienic_nozzle', 'short_nozzle'],
    description: 'Short hygienic vessel nozzle with clamp bead.',
    params: {
      radius: { type: 'number', min: 0.01, max: 0.5, default: 0.08 },
      length: { type: 'number', min: 0.03, max: 1, default: 0.18 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'y' },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'generic.flanged_nozzle',
    family: 'generic',
    kind: 'flanged_nozzle',
    semanticRole: 'flanged_nozzle',
    aliases: ['flanged_nozzle', 'process_nozzle', 'nozzle_with_flange', 'flanged_pipe_nozzle'],
    description: 'Process vessel nozzle with a visible raised flange and bolt pattern.',
    params: {
      radius: { type: 'number', min: 0.015, max: 0.8, default: 0.09 },
      length: { type: 'number', min: 0.06, max: 1.8, default: 0.26 },
      flangeRadius: { type: 'number', min: 0.03, max: 2.2, default: 0.16 },
      flangeThickness: { type: 'number', min: 0.008, max: 0.22, default: 0.025 },
      boltCount: { type: 'integer', min: 0, max: 24, default: 8 },
      includeBolts: { type: 'boolean', default: true },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'y' },
      side: { type: 'enum', values: ['front', 'back', 'left', 'right', 'top', 'bottom'] },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'generic.inspection_hatch',
    family: 'generic',
    kind: 'inspection_hatch',
    semanticRole: 'inspection_hatch',
    aliases: ['inspection_hatch', 'access_hatch', 'round_hatch'],
    description:
      'Round inspection hatch with a hinge block and handle for vessel or enclosure faces.',
    params: {
      radius: { type: 'number', min: 0.04, max: 1.2, default: 0.18 },
      thickness: { type: 'number', min: 0.006, max: 0.28, default: 0.035 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'z' },
      side: { type: 'enum', values: ['front', 'back', 'left', 'right', 'top', 'bottom'] },
      metalColor: { type: 'color', default: '#cbd5e1' },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'generic.jacket_shell',
    family: 'generic',
    kind: 'jacket_shell',
    semanticRole: 'jacket_shell',
    aliases: ['jacket_shell', 'outer_jacket', 'thermal_jacket', 'cooling_jacket', 'heating_jacket'],
    description: 'Visible outer thermal jacket sleeve for process vessels.',
    params: {
      radius: { type: 'number', min: 0.08, max: 3, default: 0.52 },
      height: { type: 'number', min: 0.12, max: 8, default: 1.1 },
      thickness: { type: 'number', min: 0.004, max: 0.12, default: 0.018 },
      opacity: { type: 'number', min: 0.08, max: 1, default: 0.28 },
      primaryColor: { type: 'color', default: '#dbe3ea' },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'generic.sight_glass',
    family: 'generic',
    kind: 'sight_glass',
    semanticRole: 'sight_glass',
    aliases: ['sight_glass', 'inspection_glass', 'view_glass', 'viewing_glass'],
    description: 'Transparent vessel inspection glass with a metal rim.',
    params: {
      length: { type: 'number', min: 0.03, max: 1.4, default: 0.18 },
      height: { type: 'number', min: 0.03, max: 1.6, default: 0.24 },
      thickness: { type: 'number', min: 0.002, max: 0.08, default: 0.012 },
      side: {
        type: 'enum',
        values: ['left', 'right', 'top', 'bottom', 'front', 'back'],
        default: 'front',
      },
      opacity: { type: 'number', min: 0.12, max: 0.9, default: 0.42 },
      color: { type: 'color', default: '#93c5fd' },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'generic.sample_valve',
    family: 'generic',
    kind: 'sample_valve',
    semanticRole: 'sample_valve',
    aliases: ['sample_valve', 'sampling_valve', 'sampling_port', 'sample_cock'],
    description: 'Small vessel sampling valve with handle.',
    params: {
      radius: { type: 'number', min: 0.008, max: 0.25, default: 0.045 },
      length: { type: 'number', min: 0.04, max: 0.8, default: 0.22 },
      side: { type: 'enum', values: ['left', 'right', 'front', 'back'], default: 'front' },
      metalColor: { type: 'color', default: '#cbd5e1' },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'generic.instrument_port',
    family: 'generic',
    kind: 'instrument_port',
    semanticRole: 'instrument_port',
    aliases: [
      'instrument_port',
      'gauge_port',
      'thermowell',
      'pressure_gauge',
      'temperature_probe',
      'sensor_port',
    ],
    description: 'Small gauge, thermowell, or instrument connection.',
    params: {
      radius: { type: 'number', min: 0.006, max: 0.22, default: 0.035 },
      length: { type: 'number', min: 0.03, max: 0.7, default: 0.16 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'y' },
      metalColor: { type: 'color', default: '#cbd5e1' },
      darkColor: { type: 'color', default: '#0f172a' },
    },
  },
  {
    id: 'generic.stainless_highlight_panel',
    family: 'generic',
    kind: 'stainless_highlight_panel',
    semanticRole: 'stainless_highlight_panel',
    aliases: [
      'stainless_highlight_panel',
      'metal_highlight_panel',
      'polished_highlight',
      'stainless_reflection',
    ],
    description:
      'Subtle polished stainless reflection patch for cylindrical or flat equipment shells.',
    params: {
      length: { type: 'number', min: 0.02, max: 1.2, default: 0.16 },
      height: { type: 'number', min: 0.04, max: 4, default: 0.6 },
      thickness: { type: 'number', min: 0.001, max: 0.05, default: 0.006 },
      side: {
        type: 'enum',
        values: ['left', 'right', 'top', 'bottom', 'front', 'back'],
        default: 'front',
      },
      opacity: { type: 'number', min: 0.12, max: 0.95, default: 0.5 },
      color: { type: 'color', default: '#f8fafc' },
    },
  },
  {
    id: 'generic.mobile_platform_chassis',
    family: 'generic',
    kind: 'mobile_platform_chassis',
    semanticRole: 'vehicle_body',
    aliases: [
      'mobile_platform_chassis',
      'mobile_chassis',
      'agv_chassis',
      'amr_chassis',
      'robot_platform_chassis',
      'low_platform_body',
    ],
    description:
      'Low rounded mobile robot or AGV chassis with dark bumper skirt, main body, top load deck, and side status seams.',
    params: {
      length: { type: 'number', min: 0.3, max: 4, default: 1.45 },
      width: { type: 'number', min: 0.24, max: 2.4, default: 0.9 },
      height: { type: 'number', min: 0.08, max: 1.2, default: 0.28 },
      cornerRadius: { type: 'number', min: 0, max: 0.5, default: 0.16 },
      primaryColor: { type: 'color', default: '#e5e7eb' },
      secondaryColor: { type: 'color', default: '#334155' },
      darkColor: { type: 'color', default: '#111827' },
      accentColor: { type: 'color', default: '#38bdf8' },
    },
  },
  {
    id: 'generic.lidar_sensor',
    family: 'generic',
    kind: 'lidar_sensor',
    semanticRole: 'navigation_sensor',
    aliases: [
      'lidar',
      'lidar_sensor',
      'laser_scanner',
      'navigation_sensor',
      'safety_scanner',
      'front_scanner',
    ],
    description: 'Compact lidar or laser safety scanner with dark housing and translucent lens.',
    params: {
      radius: { type: 'number', min: 0.012, max: 0.18, default: 0.045 },
      height: { type: 'number', min: 0.006, max: 0.35 },
      length: { type: 'number', min: 0.006, max: 0.35 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'x' },
      darkColor: { type: 'color', default: '#0f172a' },
      accentColor: { type: 'color', default: '#38bdf8' },
    },
  },
  {
    id: 'generic.emergency_stop_button',
    family: 'generic',
    kind: 'emergency_stop_button',
    semanticRole: 'emergency_stop_button',
    aliases: ['emergency_stop', 'emergency_stop_button', 'e_stop', 'e_stop_button', 'stop_button'],
    description: 'Red emergency stop button with dark base and protective guard ring.',
    params: {
      radius: { type: 'number', min: 0.012, max: 0.16, default: 0.04 },
      height: { type: 'number', min: 0.006, max: 0.25 },
      length: { type: 'number', min: 0.006, max: 0.25 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'y' },
      color: { type: 'color', default: '#ef4444' },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'generic.status_light_strip',
    family: 'generic',
    kind: 'status_light_strip',
    semanticRole: 'status_light_strip',
    aliases: [
      'status_light_strip',
      'light_strip',
      'led_strip',
      'signal_light_strip',
      'indicator_strip',
    ],
    description:
      'Thin colored status light strip for AGVs, robot cells, and industrial enclosures.',
    params: {
      length: { type: 'number', min: 0.04, max: 4, default: 0.7 },
      height: { type: 'number', min: 0.008, max: 0.25, default: 0.035 },
      thickness: { type: 'number', min: 0.002, max: 0.08, default: 0.012 },
      side: { type: 'enum', values: ['left', 'right', 'front', 'back'], default: 'left' },
      color: { type: 'color', default: '#38bdf8' },
      accentColor: { type: 'color', default: '#38bdf8' },
    },
  },
  {
    id: 'generic.operator_panel',
    family: 'generic',
    kind: 'operator_panel',
    semanticRole: 'control_panel',
    aliases: ['operator_panel', 'hmi_panel', 'control_pendant', 'operator_console'],
    description: 'Operator HMI/control panel with enclosure body, display screen, and buttons.',
    params: {
      width: { type: 'number', min: 0.12, max: 1.2, default: 0.32 },
      height: { type: 'number', min: 0.18, max: 2, default: 0.62 },
      depth: { type: 'number', min: 0.03, max: 0.5, default: 0.12 },
      primaryColor: { type: 'color', default: '#e5e7eb' },
      darkColor: { type: 'color', default: '#0f172a' },
      accentColor: { type: 'color', default: '#22c55e' },
    },
  },
  {
    id: 'generic.guard_fence',
    family: 'generic',
    kind: 'guard_fence',
    semanticRole: 'safety_barrier',
    aliases: ['guard_fence', 'safety_fence', 'safety_guard', 'guard_rail', 'barrier_fence'],
    description: 'Reusable safety fence or guard rail with posts and horizontal rails.',
    params: {
      length: { type: 'number', min: 0.25, max: 8, default: 1.8 },
      height: { type: 'number', min: 0.2, max: 3, default: 0.9 },
      width: { type: 'number', min: 0.02, max: 0.5, default: 0.08 },
      count: { type: 'integer', min: 2, max: 12, default: 4 },
      radius: { type: 'number', min: 0.006, max: 0.08, default: 0.018 },
      color: { type: 'color', default: '#facc15' },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'generic.pallet_table',
    family: 'generic',
    kind: 'pallet_table',
    semanticRole: 'pallet_table',
    aliases: ['pallet_table', 'pallet_station', 'pallet_deck', 'fixture_table'],
    description: 'Reusable pallet or fixture table with deck and four support legs.',
    params: {
      length: { type: 'number', min: 0.25, max: 4, default: 1 },
      width: { type: 'number', min: 0.2, max: 3, default: 0.7 },
      height: { type: 'number', min: 0.08, max: 1.2, default: 0.28 },
      primaryColor: { type: 'color', default: '#475569' },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'generic.bearing_block',
    family: 'generic',
    kind: 'bearing_block',
    semanticRole: 'bearing_block',
    aliases: [
      'bearing_block',
      'pillow_block',
      'pillow_block_bearing',
      'bearing_housing',
      'mounted_bearing',
    ],
    description:
      'Mounted bearing or pillow block with base, housing, bearing ring, bore, and mounting bolts.',
    params: {
      length: { type: 'number', min: 0.12, max: 1.6, default: 0.42 },
      width: { type: 'number', min: 0.08, max: 1, default: 0.22 },
      height: { type: 'number', min: 0.08, max: 1.2, default: 0.26 },
      radius: { type: 'number', min: 0.015, max: 0.4, default: 0.07 },
      metalColor: { type: 'color', default: '#64748b' },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'generic.coupling_guard',
    family: 'generic',
    kind: 'coupling_guard',
    semanticRole: 'coupling_guard',
    aliases: ['coupling_guard', 'shaft_guard', 'coupling_cover', 'rotating_shaft_guard'],
    description: 'Half-cylinder safety guard over a shaft coupling with end flange plates.',
    params: {
      length: { type: 'number', min: 0.16, max: 2.4, default: 0.58 },
      radius: { type: 'number', min: 0.04, max: 0.7, default: 0.16 },
      thickness: { type: 'number', min: 0.006, max: 0.16, default: 0.028 },
      color: { type: 'color', default: '#facc15' },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'generic.motor_gearbox_unit',
    family: 'generic',
    kind: 'motor_gearbox_unit',
    semanticRole: 'drive_unit',
    aliases: [
      'motor_gearbox_unit',
      'motor_reducer_unit',
      'drive_unit',
      'gearmotor',
      'motor_gearbox',
    ],
    description: 'Compact drive unit with ribbed motor, gearbox housing, and output shaft.',
    params: {
      length: { type: 'number', min: 0.3, max: 4, default: 1.05 },
      height: { type: 'number', min: 0.12, max: 1.8, default: 0.38 },
      radius: { type: 'number', min: 0.05, max: 0.8, default: 0.18 },
      primaryColor: { type: 'color', default: '#64748b' },
      secondaryColor: { type: 'color', default: '#475569' },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'generic.pipe_manifold',
    family: 'generic',
    kind: 'pipe_manifold',
    semanticRole: 'pipe_manifold',
    aliases: ['pipe_manifold', 'manifold', 'header_pipe', 'branch_manifold'],
    description: 'Process pipe manifold with a header pipe and repeated branch ports.',
    params: {
      length: { type: 'number', min: 0.25, max: 6, default: 1.2 },
      radius: { type: 'number', min: 0.012, max: 0.4, default: 0.065 },
      count: { type: 'integer', min: 2, max: 10, default: 4 },
      metalColor: { type: 'color', default: '#94a3b8' },
    },
  },
  {
    id: 'generic.hopper_body',
    family: 'generic',
    kind: 'hopper_body',
    semanticRole: 'hopper_body',
    aliases: ['hopper_body', 'feed_hopper', 'material_hopper', 'inlet_hopper'],
    description: 'Tapered material hopper with outlet throat and support legs.',
    params: {
      length: { type: 'number', min: 0.25, max: 4, default: 0.9 },
      width: { type: 'number', min: 0.2, max: 3, default: 0.7 },
      height: { type: 'number', min: 0.25, max: 3.5, default: 0.8 },
      topLengthScale: { type: 'number', min: 0.2, max: 3, default: 1.65 },
      topWidthScale: { type: 'number', min: 0.2, max: 3, default: 1.45 },
      primaryColor: { type: 'color', default: '#94a3b8' },
      darkColor: { type: 'color', default: '#374151' },
    },
  },
  {
    id: 'generic.conical_hopper',
    family: 'generic',
    kind: 'conical_hopper',
    semanticRole: 'conical_hopper',
    aliases: ['conical_hopper', 'cone_hopper', 'cone_discharge_hopper'],
    description: 'Round conical discharge hopper with outlet collar and optional support legs.',
    params: {
      radiusTop: { type: 'number', min: 0.08, max: 3, default: 0.42 },
      radiusBottom: { type: 'number', min: 0.02, max: 1.2, default: 0.08 },
      outletRadius: { type: 'number', min: 0.02, max: 1.2, default: 0.08 },
      height: { type: 'number', min: 0.18, max: 5, default: 0.82 },
      radialSegments: { type: 'integer', min: 4, max: 64, default: 32 },
      includeSupportLegs: { type: 'boolean', default: true },
      primaryColor: { type: 'color', default: '#94a3b8' },
      darkColor: { type: 'color', default: '#374151' },
    },
  },
  {
    id: 'generic.structural_tower_frame',
    family: 'generic',
    kind: 'structural_tower_frame',
    semanticRole: 'preheater_tower_body',
    aliases: [
      'structural_tower_frame',
      'tower_frame',
      'steel_tower_frame',
      'preheater_tower_frame',
      'multi_level_tower_frame',
      '塔架',
      '钢结构塔架',
    ],
    description:
      'Multi-level industrial steel tower frame with columns, beams, grated decks, guard rails, and ladder.',
    params: {
      length: { type: 'number', min: 0.8, max: 12, default: 2.2 },
      width: { type: 'number', min: 0.6, max: 8, default: 1.6 },
      height: { type: 'number', min: 1.4, max: 18, default: 6 },
      levelCount: { type: 'integer', min: 2, max: 9, default: 5 },
      bayCount: { type: 'integer', min: 1, max: 5, default: 2 },
      stairFlights: { type: 'integer', min: 2, max: 9, default: 5 },
      stairPlacement: { type: 'enum', values: ['inside', 'outside'], default: 'inside' },
      externalStairs: { type: 'boolean', default: true },
      includeDiagonalBraces: { type: 'boolean', default: true },
      thickness: { type: 'number', min: 0.025, max: 0.18, default: 0.06 },
      metalColor: { type: 'color', default: '#475569' },
      darkColor: { type: 'color', default: '#111827' },
      accentColor: { type: 'color', default: '#1f2937' },
    },
  },
  {
    id: 'generic.helical_stair',
    family: 'generic',
    kind: 'helical_stair',
    semanticRole: 'external_spiral_stair',
    aliases: [
      'helical_stair',
      'spiral_stair',
      'external_spiral_stair',
      'tower_spiral_stair',
      'wraparound_stair',
      'ring_stair',
      '环形楼梯',
      '螺旋楼梯',
      '塔外盘梯',
    ],
    description:
      'Wraparound helical access stair for tall process columns, with radial treads, posts, and guard rails.',
    params: {
      height: { type: 'number', min: 0.8, max: 18, default: 6 },
      innerRadius: { type: 'number', min: 0.08, max: 6, default: 0.9 },
      outerRadius: { type: 'number', min: 0.16, max: 7, default: 1.22 },
      width: { type: 'number', min: 0.12, max: 1.2, default: 0.32 },
      depth: { type: 'number', min: 0.04, max: 0.9, default: 0.22 },
      thickness: { type: 'number', min: 0.012, max: 0.16, default: 0.035 },
      stepCount: { type: 'integer', min: 8, max: 72, default: 18 },
      ringCount: { type: 'integer', min: 8, max: 72, default: 16 },
      sweepAngle: { type: 'number', min: 2.35, max: 31.42, default: 12.57 },
      startAngle: { type: 'number', min: -6.28, max: 6.28, default: 0 },
      railingHeight: { type: 'number', min: 0.18, max: 1.1, default: 0.42 },
      wireRadius: { type: 'number', min: 0.004, max: 0.08, default: 0.018 },
      metalColor: { type: 'color', default: '#64748b' },
      color: { type: 'color', default: '#94a3b8' },
    },
  },
  {
    id: 'generic.helical_ladder',
    family: 'generic',
    kind: 'helical_ladder',
    semanticRole: 'external_spiral_ladder',
    aliases: [
      'helical_ladder',
      'spiral_ladder',
      'spiral_access_ladder',
      'spiral_access_stair',
      'tower_helical_ladder',
      'column_spiral_ladder',
      'wraparound_ladder',
      '环绕梯',
      '螺旋梯',
      '塔外螺旋梯',
    ],
    description:
      'Dedicated wraparound ladder for process columns and towers, with helical treads, posts, landings, and guard rails.',
    params: {
      height: { type: 'number', min: 0.8, max: 18, default: 6 },
      innerRadius: { type: 'number', min: 0.08, max: 6, default: 0.9 },
      outerRadius: { type: 'number', min: 0.16, max: 7, default: 1.22 },
      width: { type: 'number', min: 0.12, max: 1.2, default: 0.32 },
      depth: { type: 'number', min: 0.04, max: 0.9, default: 0.22 },
      thickness: { type: 'number', min: 0.012, max: 0.16, default: 0.035 },
      stepCount: { type: 'integer', min: 8, max: 72, default: 18 },
      ringCount: { type: 'integer', min: 8, max: 72, default: 16 },
      sweepAngle: { type: 'number', min: 2.35, max: 31.42, default: 12.57 },
      startAngle: { type: 'number', min: -6.28, max: 6.28, default: 0 },
      railingHeight: { type: 'number', min: 0.18, max: 1.1, default: 0.42 },
      wireRadius: { type: 'number', min: 0.004, max: 0.08, default: 0.018 },
      metalColor: { type: 'color', default: '#64748b' },
      color: { type: 'color', default: '#94a3b8' },
    },
  },
  {
    id: 'generic.cyclone_separator_unit',
    family: 'generic',
    kind: 'cyclone_separator_unit',
    semanticRole: 'preheater_cyclone',
    aliases: [
      'cyclone_separator_unit',
      'cyclone_unit',
      'preheater_cyclone',
      'cyclone_stage',
      'cyclone_separator',
      '旋风筒',
      '旋风分离器',
    ],
    description:
      'Cyclone separator stage with cylindrical body, conical hopper, top outlet, tangential inlet, and meal drop pipe.',
    params: {
      height: { type: 'number', min: 0.45, max: 4, default: 1.2 },
      radius: { type: 'number', min: 0.08, max: 1.4, default: 0.26 },
      bodyHeight: { type: 'number', min: 0.2, max: 2.8 },
      depth: { type: 'number', min: 0.08, max: 1.6 },
      length: { type: 'number', min: 0.05, max: 1.4 },
      thickness: { type: 'number', min: 0.025, max: 0.7 },
      primaryColor: { type: 'color', default: '#9ca3af' },
      metalColor: { type: 'color', default: '#64748b' },
      darkColor: { type: 'color', default: '#1f2937' },
    },
  },
  {
    id: 'generic.service_platform',
    family: 'generic',
    kind: 'service_platform',
    semanticRole: 'service_platform',
    aliases: ['service_platform', 'maintenance_platform', 'inspection_platform', 'access_deck'],
    description: 'Service or inspection platform with deck, posts, guard rails, and access ladder.',
    params: {
      length: { type: 'number', min: 0.3, max: 6, default: 1.2 },
      width: { type: 'number', min: 0.2, max: 3, default: 0.65 },
      height: { type: 'number', min: 0.2, max: 3.5, default: 0.9 },
      overallHeight: { type: 'number', min: 0.18, max: 1.4, default: 0.4 },
      detailLevel: { type: 'enum', values: ['low', 'medium', 'high'], default: 'medium' },
      metalColor: { type: 'color', default: '#64748b' },
      color: { type: 'color', default: '#facc15' },
    },
  },
  {
    id: 'generic.platform_with_ladder',
    family: 'generic',
    kind: 'platform_with_ladder',
    semanticRole: 'service_platform',
    aliases: ['platform_with_ladder', 'maintenance_platform_ladder', 'access_platform_ladder'],
    description: 'Service platform with guard rails and explicit ladder rails/rungs.',
    params: {
      length: { type: 'number', min: 0.3, max: 6, default: 1.2 },
      width: { type: 'number', min: 0.2, max: 3, default: 0.65 },
      height: { type: 'number', min: 0.2, max: 3.5, default: 0.9 },
      overallHeight: { type: 'number', min: 0.18, max: 1.4, default: 0.4 },
      detailLevel: { type: 'enum', values: ['low', 'medium', 'high'], default: 'medium' },
      rungCount: { type: 'integer', min: 3, max: 16, default: 6 },
      metalColor: { type: 'color', default: '#64748b' },
      color: { type: 'color', default: '#facc15' },
    },
  },
  {
    id: 'generic.chimney_stack',
    family: 'generic',
    kind: 'chimney_stack',
    semanticRole: 'stack_shell',
    aliases: ['chimney_stack', 'process_stack', 'smokestack', 'exhaust_stack', 'stack_shell'],
    description:
      'Tall industrial exhaust stack with optional bands, platform, and inlet connection.',
    params: {
      height: { type: 'number', min: 0.8, max: 30, default: 6 },
      radius: { type: 'number', min: 0.05, max: 2, default: 0.28 },
      thickness: { type: 'number', min: 0.01, max: 0.2, default: 0.04 },
      bandCount: { type: 'integer', min: 0, max: 8, default: 3 },
      warningStripes: { type: 'boolean', default: false },
      metalColor: { type: 'color', default: '#9ca3af' },
      accentColor: { type: 'color', default: '#ef4444' },
    },
  },
]

export const KIOSK_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'kiosk.kiosk_body',
    family: 'kiosk',
    kind: 'kiosk_body',
    semanticRole: 'kiosk_body',
    aliases: ['body', 'kiosk_body', 'booth_body', 'stall_body', 'small_building_body', 'walls'],
    required: true,
    description: 'Main kiosk or booth wall volume.',
    params: {
      length: { type: 'number', min: 0.4, max: 8, default: 1.8 },
      width: { type: 'number', min: 0.3, max: 5, default: 1.2 },
      height: { type: 'number', min: 0.4, max: 5, default: 1.65 },
      primaryColor: { type: 'color', default: '#d1d5db' },
      cornerRadius: { type: 'number', min: 0, max: 0.3 },
    },
  },
  {
    id: 'kiosk.kiosk_roof',
    family: 'kiosk',
    kind: 'kiosk_roof',
    semanticRole: 'roof',
    aliases: ['roof', 'kiosk_roof', 'booth_roof', 'pavilion_roof', 'shed_roof'],
    required: true,
    attachTo: 'kiosk_body',
    layoutRole: 'top_overhang',
    description: 'Overhanging kiosk roof.',
    params: {
      length: { type: 'number', min: 0.4, max: 9, default: 2.1 },
      width: { type: 'number', min: 0.3, max: 6, default: 1.45 },
      height: { type: 'number', min: 0.04, max: 1.2, default: 0.28 },
      color: { type: 'color', default: '#7f1d1d' },
      variant: { type: 'enum', values: ['pitched', 'flat'], default: 'pitched' },
    },
  },
  {
    id: 'kiosk.kiosk_opening',
    family: 'kiosk',
    kind: 'kiosk_opening',
    semanticRole: 'opening',
    aliases: ['opening', 'window', 'service_window', 'ticket_window', 'serving_window', 'door'],
    required: true,
    attachTo: 'kiosk_body',
    layoutRole: 'front_service_opening',
    description: 'Front service window, ticket window, or door opening.',
    params: {
      length: { type: 'number', min: 0.08, max: 5, default: 0.8 },
      height: { type: 'number', min: 0.08, max: 4, default: 0.75 },
      thickness: { type: 'number', min: 0.004, max: 0.5, default: 0.035 },
      color: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'kiosk.kiosk_counter',
    family: 'kiosk',
    kind: 'kiosk_counter',
    semanticRole: 'service_counter',
    aliases: ['counter', 'service_counter', 'serving_counter', 'sales_counter', 'shelf'],
    attachTo: 'kiosk_opening',
    layoutRole: 'front_counter',
    description: 'Front service counter or shelf.',
    params: {
      length: { type: 'number', min: 0.08, max: 6, default: 1 },
      width: { type: 'number', min: 0.04, max: 2, default: 0.28 },
      thickness: { type: 'number', min: 0.02, max: 0.6, default: 0.08 },
      color: { type: 'color', default: '#9ca3af' },
    },
  },
  {
    id: 'kiosk.kiosk_sign',
    family: 'kiosk',
    kind: 'kiosk_sign',
    semanticRole: 'sign_panel',
    aliases: ['sign', 'signage', 'sign_panel', 'shop_sign', 'name_sign', 'ticket_sign'],
    attachTo: 'kiosk_body',
    layoutRole: 'front_upper_sign',
    description: 'Front sign panel.',
    params: {
      length: { type: 'number', min: 0.08, max: 6, default: 1 },
      height: { type: 'number', min: 0.04, max: 1.5, default: 0.26 },
      thickness: { type: 'number', min: 0.004, max: 0.4, default: 0.035 },
      accentColor: { type: 'color', default: '#facc15' },
    },
  },
  {
    id: 'kiosk.kiosk_awning',
    family: 'kiosk',
    kind: 'kiosk_awning',
    semanticRole: 'awning',
    aliases: ['awning', 'canopy', 'sunshade', 'front_awning'],
    attachTo: 'kiosk_body',
    layoutRole: 'front_canopy',
    description: 'Optional small canopy/awning over the opening.',
    params: {
      length: { type: 'number', min: 0.08, max: 7, default: 1.25 },
      width: { type: 'number', min: 0.04, max: 2.4, default: 0.45 },
      thickness: { type: 'number', min: 0.02, max: 0.8, default: 0.08 },
      color: { type: 'color', default: '#ef4444' },
    },
  },
]

export const PUMP_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'pump.skid_base',
    family: 'pump',
    kind: 'skid_base',
    semanticRole: 'support_base',
    aliases: ['base', 'skid', 'skid_base', 'pump_base', 'baseplate', 'foundation'],
    required: true,
    layoutRole: 'bottom_skid',
    description: 'Pump skid base or baseplate.',
    params: {
      length: { type: 'number', min: 0.3, max: 6, default: 1.2 },
      width: { type: 'number', min: 0.12, max: 3, default: 0.55 },
      height: { type: 'number', min: 0.02, max: 0.8, default: 0.08 },
      metalColor: { type: 'color', default: '#64748b' },
    },
  },
  {
    id: 'pump.ribbed_motor_body',
    family: 'pump',
    kind: 'ribbed_motor_body',
    semanticRole: 'drive_motor',
    aliases: ['motor', 'electric_motor', 'drive_motor', 'motor_body', 'ribbed_motor'],
    required: true,
    attachTo: 'skid_base',
    layoutRole: 'motor_on_skid',
    description: 'Ribbed electric motor driving the pump.',
    params: {
      length: { type: 'number', min: 0.12, max: 3, default: 0.48 },
      radius: { type: 'number', min: 0.04, max: 1, default: 0.18 },
      count: { type: 'integer', min: 3, max: 20, default: 8 },
      slatCount: { type: 'integer', min: 3, max: 20 },
      primaryColor: { type: 'color', default: '#64748b' },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'pump.volute_casing',
    family: 'pump',
    kind: 'volute_casing',
    semanticRole: 'volute_casing',
    aliases: ['volute', 'pump_casing', 'volute_casing', 'casing', 'housing', 'pump_body'],
    required: true,
    attachTo: 'skid_base',
    layoutRole: 'front_pump_casing',
    description: 'Spiral volute casing for a centrifugal pump or blower.',
    params: {
      radius: { type: 'number', min: 0.05, max: 1.5, default: 0.22 },
      depth: { type: 'number', min: 0.04, max: 1.2, default: 0.14 },
      primaryColor: { type: 'color', default: '#64748b' },
    },
  },
  {
    id: 'pump.inlet_port',
    family: 'pump',
    kind: 'inlet_port',
    semanticRole: 'inlet_port',
    aliases: ['inlet', 'suction', 'suction_port', 'inlet_port', 'nozzle_inlet'],
    required: true,
    attachTo: 'volute_casing',
    layoutRole: 'volute_inlet',
    description: 'Pump suction inlet nozzle.',
    params: {
      radius: { type: 'number', min: 0.02, max: 0.7, default: 0.07 },
      length: { type: 'number', min: 0.04, max: 1.5, default: 0.22 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'z' },
      metalColor: { type: 'color', default: '#94a3b8' },
    },
  },
  {
    id: 'pump.outlet_port',
    family: 'pump',
    kind: 'outlet_port',
    semanticRole: 'outlet_port',
    aliases: ['outlet', 'discharge', 'discharge_port', 'outlet_port', 'nozzle_outlet'],
    required: true,
    attachTo: 'volute_casing',
    layoutRole: 'volute_outlet',
    description: 'Pump discharge outlet nozzle.',
    params: {
      radius: { type: 'number', min: 0.02, max: 0.7, default: 0.06 },
      length: { type: 'number', min: 0.04, max: 1.5, default: 0.2 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'x' },
      metalColor: { type: 'color', default: '#94a3b8' },
    },
  },
  {
    id: 'pump.flange_ring',
    family: 'pump',
    kind: 'flange_ring',
    semanticRole: 'flange',
    aliases: ['flange', 'flanges', 'flange_ring', 'pipe_flange'],
    attachTo: 'inlet_port',
    layoutRole: 'port_flange',
    description: 'Circular flange ring on a pump port.',
    params: {
      radius: { type: 'number', min: 0.03, max: 0.9, default: 0.12 },
      tubeRadius: { type: 'number', min: 0.004, max: 0.15, default: 0.018 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'z' },
      detailLevel: { type: 'enum', values: ['low', 'medium', 'high'], default: 'medium' },
      boltCount: { type: 'integer', min: 4, max: 16, default: 8 },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'pump.impeller_blades',
    family: 'pump',
    kind: 'impeller_blades',
    semanticRole: 'impeller',
    aliases: ['impeller', 'impeller_blades', 'pump_impeller', 'rotor'],
    attachTo: 'volute_casing',
    layoutRole: 'inside_volute',
    description: 'Visible impeller blade set.',
    params: {
      count: { type: 'integer', min: 3, max: 14, default: 7 },
      radius: { type: 'number', min: 0.03, max: 1, default: 0.14 },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'pump.control_box',
    family: 'pump',
    kind: 'control_box',
    semanticRole: 'control_box',
    aliases: ['control_box', 'junction_box', 'terminal_box', 'controller'],
    attachTo: 'ribbed_motor_body',
    layoutRole: 'motor_top_box',
    description: 'Small control or terminal box on the motor.',
    params: {
      length: { type: 'number', min: 0.04, max: 1, default: 0.16 },
      width: { type: 'number', min: 0.03, max: 0.8, default: 0.12 },
      height: { type: 'number', min: 0.02, max: 0.6, default: 0.08 },
      primaryColor: { type: 'color', default: '#1f2937' },
    },
  },
]

export const CONVEYOR_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'conveyor.conveyor_frame',
    family: 'conveyor',
    kind: 'conveyor_frame',
    semanticRole: 'conveyor_frame',
    aliases: ['conveyor', 'belt_conveyor', 'frame', 'conveyor_frame', 'support_frame'],
    required: true,
    layoutRole: 'long_frame',
    description: 'Long conveyor support frame with rails and legs.',
    params: {
      length: { type: 'number', min: 0.4, max: 12, default: 3 },
      width: { type: 'number', min: 0.12, max: 3, default: 0.7 },
      height: { type: 'number', min: 0.12, max: 2.5, default: 0.65 },
      radius: { type: 'number', min: 0.006, max: 0.15, default: 0.025 },
      legCount: { type: 'integer', min: 2, max: 16 },
      metalColor: { type: 'color', default: '#94a3b8' },
    },
  },
  {
    id: 'conveyor.roller_array',
    family: 'conveyor',
    kind: 'roller_array',
    semanticRole: 'roller_array',
    aliases: ['rollers', 'roller_array', 'roller_bed', 'idlers'],
    required: true,
    attachTo: 'conveyor_frame',
    layoutRole: 'rollers_on_frame',
    description: 'Repeated rollers across the conveyor bed.',
    params: {
      count: { type: 'integer', min: 2, max: 32, default: 9 },
      length: { type: 'number', min: 0.3, max: 12, default: 2.8 },
      width: { type: 'number', min: 0.08, max: 3, default: 0.62 },
      radius: { type: 'number', min: 0.008, max: 0.2, default: 0.035 },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'conveyor.belt_surface',
    family: 'conveyor',
    kind: 'belt_surface',
    semanticRole: 'belt_surface',
    aliases: ['belt', 'belt_surface', 'conveyor_belt', 'rubber_belt'],
    required: true,
    attachTo: 'conveyor_frame',
    layoutRole: 'top_belt',
    description: 'Continuous dark belt surface.',
    params: {
      length: { type: 'number', min: 0.3, max: 12, default: 2.9 },
      width: { type: 'number', min: 0.08, max: 3, default: 0.62 },
      height: { type: 'number', min: 0.004, max: 0.16, default: 0.025 },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'conveyor.ribbed_motor_body',
    family: 'conveyor',
    kind: 'ribbed_motor_body',
    semanticRole: 'drive_motor',
    aliases: ['drive_motor', 'motor', 'gear_motor', 'conveyor_motor'],
    attachTo: 'conveyor_frame',
    layoutRole: 'end_drive_motor',
    description: 'Side-mounted conveyor drive motor.',
    params: {
      length: { type: 'number', min: 0.08, max: 2, default: 0.28 },
      radius: { type: 'number', min: 0.03, max: 0.5, default: 0.08 },
      primaryColor: { type: 'color', default: '#64748b' },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
]

export const ELECTRICAL_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'electrical.electrical_cabinet',
    family: 'electrical',
    kind: 'electrical_cabinet',
    semanticRole: 'electrical_cabinet',
    aliases: [
      'electrical_cabinet',
      'control_cabinet',
      'power_cabinet',
      'switchgear',
      'control_panel',
      'cabinet',
    ],
    required: true,
    layoutRole: 'upright_cabinet',
    description: 'Industrial electrical or control cabinet body.',
    params: {
      length: { type: 'number', min: 0.18, max: 4, default: 0.8 },
      width: { type: 'number', min: 0.08, max: 2, default: 0.32 },
      height: { type: 'number', min: 0.3, max: 4, default: 1.6 },
      doorCount: { type: 'integer', min: 1, max: 4 },
      slatCount: { type: 'integer', min: 2, max: 10 },
      primaryColor: { type: 'color', default: '#d1d5db' },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'electrical.cable_tray',
    family: 'electrical',
    kind: 'cable_tray',
    semanticRole: 'cable_tray',
    aliases: ['cable_tray', 'wire_tray', 'cable_duct', 'cable_ladder'],
    attachTo: 'electrical_cabinet',
    layoutRole: 'top_cable_tray',
    description: 'Cable tray or cable duct connected to the cabinet.',
    params: {
      length: { type: 'number', min: 0.15, max: 8, default: 1.1 },
      width: { type: 'number', min: 0.04, max: 1, default: 0.16 },
      height: { type: 'number', min: 0.02, max: 0.5, default: 0.08 },
      slatCount: { type: 'integer', min: 2, max: 18 },
      metalColor: { type: 'color', default: '#94a3b8' },
    },
  },
]

export const PIPE_SYSTEM_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'pipe_system.pipe_run',
    family: 'pipe_system',
    kind: 'pipe_run',
    semanticRole: 'pipe_run',
    aliases: ['pipe', 'pipe_run', 'straight_pipe', 'pipeline', 'process_pipe', 'piping'],
    required: true,
    layoutRole: 'straight_run',
    description: 'Straight industrial pipe run.',
    params: {
      length: { type: 'number', min: 0.15, max: 20, default: 2 },
      radius: { type: 'number', min: 0.01, max: 1, default: 0.06 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'x' },
      metalColor: { type: 'color', default: '#94a3b8' },
    },
  },
  {
    id: 'pipe_system.pipe_elbow',
    family: 'pipe_system',
    kind: 'pipe_elbow',
    semanticRole: 'pipe_elbow',
    aliases: ['elbow', 'pipe_elbow', 'bend', 'pipe_bend', 'elbow90'],
    attachTo: 'pipe_run',
    layoutRole: 'pipe_bend',
    description: 'Ninety-degree pipe elbow.',
    params: {
      radius: { type: 'number', min: 0.01, max: 1, default: 0.055 },
      bendRadius: { type: 'number', min: 0.03, max: 2, default: 0.22 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'x' },
      metalColor: { type: 'color', default: '#94a3b8' },
    },
  },
  {
    id: 'pipe_system.flange_ring',
    family: 'pipe_system',
    kind: 'flange_ring',
    semanticRole: 'flange',
    aliases: ['flange', 'pipe_flange', 'flange_ring'],
    attachTo: 'pipe_run',
    layoutRole: 'pipe_end_flange',
    description: 'Pipe flange ring.',
    params: {
      radius: { type: 'number', min: 0.02, max: 1.2, default: 0.09 },
      tubeRadius: { type: 'number', min: 0.004, max: 0.18, default: 0.014 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'x' },
      detailLevel: { type: 'enum', values: ['low', 'medium', 'high'], default: 'medium' },
      boltCount: { type: 'integer', min: 4, max: 16, default: 8 },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'pipe_system.valve_body',
    family: 'pipe_system',
    kind: 'valve_body',
    semanticRole: 'valve_body',
    aliases: ['valve', 'inline_valve', 'valve_body'],
    attachTo: 'pipe_run',
    layoutRole: 'inline_valve',
    description: 'Inline valve body for a pipe system.',
    params: {
      length: { type: 'number', min: 0.08, max: 2, default: 0.32 },
      radius: { type: 'number', min: 0.02, max: 1, default: 0.09 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'x' },
      valveStyle: { type: 'string' },
      metalColor: { type: 'color', default: '#64748b' },
    },
  },
]

export const TANK_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'tank.cylindrical_tank',
    family: 'tank',
    kind: 'cylindrical_tank',
    aliases: ['tank', 'storage_tank', 'vessel', 'pressure_vessel', 'vertical_tank', '储罐', '罐体'],
    required: true,
    layoutRole: 'vessel_shell',
    description: 'Vertical or horizontal storage tank / pressure vessel shell.',
    params: {
      length: { type: 'number', min: 0.2, max: 10, default: 2.4 },
      radius: { type: 'number', min: 0.05, max: 3, default: 0.6 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'y' },
      primaryColor: { type: 'color', default: '#94a3b8' },
    },
  },
  {
    id: 'tank.cooling_tower_shell',
    family: 'tank',
    kind: 'cooling_tower_shell',
    semanticRole: 'cooling_tower_shell',
    aliases: [
      'cooling_tower_shell',
      'natural_draft_cooling_tower',
      'hyperboloid_cooling_tower',
      'cooling_tower',
    ],
    required: true,
    layoutRole: 'cooling_tower_shell',
    description: 'Hyperboloid natural-draft cooling tower shell.',
    params: {
      radius: { type: 'number', min: 0.25, max: 6, default: 1.15 },
      waistRadius: { type: 'number', min: 0.16, max: 5, default: 0.72 },
      topRadius: { type: 'number', min: 0.2, max: 7, default: 1.08 },
      height: { type: 'number', min: 1.8, max: 24, default: 7.2 },
      primaryColor: { type: 'color', default: '#f8fafc' },
    },
  },
  {
    id: 'tank.cooling_tower_rim',
    family: 'tank',
    kind: 'cooling_tower_rim',
    semanticRole: 'top_steam_opening',
    aliases: ['cooling_tower_rim', 'cooling_tower_opening', 'cooling_tower_top_rim'],
    attachTo: 'cooling_tower_shell',
    layoutRole: 'cooling_tower_top_opening',
    description: 'Open circular rim at the top of a natural-draft cooling tower.',
    params: {
      radius: { type: 'number', min: 0.16, max: 7, default: 1.1 },
      tubeRadius: { type: 'number', min: 0.006, max: 0.28, default: 0.05 },
      primaryColor: { type: 'color', default: '#ffffff' },
    },
  },
  {
    id: 'tank.skid_base',
    family: 'tank',
    kind: 'skid_base',
    semanticRole: 'support_base',
    aliases: ['base', 'skid', 'saddle', 'support_base', 'tank_base', '支座'],
    attachTo: 'cylindrical_tank',
    layoutRole: 'tank_support',
    description: 'Tank support base or saddle.',
    params: {
      length: { type: 'number', min: 0.2, max: 10, default: 1.5 },
      width: { type: 'number', min: 0.08, max: 4, default: 0.8 },
      height: { type: 'number', min: 0.02, max: 1, default: 0.12 },
      metalColor: { type: 'color', default: '#64748b' },
    },
  },
  {
    id: 'tank.flange_ring',
    family: 'tank',
    kind: 'flange_ring',
    semanticRole: 'flange_ring',
    aliases: ['flange_ring', 'riding_ring', 'tyre_ring', 'girth_gear', 'support_ring'],
    attachTo: 'cylindrical_tank',
    layoutRole: 'shell_ring',
    description: 'Reusable vessel or kiln shell ring, including riding rings and girth gears.',
    params: {
      radius: { type: 'number', min: 0.02, max: 3, default: 0.6 },
      tubeRadius: { type: 'number', min: 0.004, max: 0.3, default: 0.04 },
      depth: { type: 'number', min: 0.006, max: 0.3, default: 0.035 },
      detailLevel: { type: 'enum', values: ['low', 'medium', 'high'], default: 'medium' },
      boltCount: { type: 'integer', min: 3, max: 24, default: 6 },
      includeBolts: { type: 'boolean', default: true },
      metalColor: { type: 'color', default: '#64748b' },
    },
  },
  {
    id: 'tank.bearing_block',
    family: 'tank',
    kind: 'bearing_block',
    semanticRole: 'bearing_block',
    aliases: ['bearing_block', 'support_roller', 'trunnion_roller', 'pillow_block'],
    attachTo: 'cylindrical_tank',
    layoutRole: 'shell_support_roller',
    description: 'Mounted bearing or support roller block for horizontal vessels and rotary kilns.',
    params: {
      length: { type: 'number', min: 0.12, max: 1.6, default: 0.42 },
      width: { type: 'number', min: 0.08, max: 1, default: 0.22 },
      height: { type: 'number', min: 0.08, max: 1.2, default: 0.26 },
      radius: { type: 'number', min: 0.015, max: 0.4, default: 0.07 },
      metalColor: { type: 'color', default: '#64748b' },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'tank.support_roller_pair',
    family: 'tank',
    kind: 'support_roller_pair',
    semanticRole: 'support_roller',
    aliases: [
      'support_roller_pair',
      'support_roller_station',
      'trunnion_roller_pair',
      'kiln_support_roller',
      '托轮组',
    ],
    attachTo: 'cylindrical_tank',
    layoutRole: 'kiln_support_station',
    description:
      'Rotary kiln support station with a foundation, two trunnion rollers, and a small thrust roller.',
    params: {
      length: { type: 'number', min: 0.28, max: 3, default: 0.9 },
      width: { type: 'number', min: 0.28, max: 4, default: 1.18 },
      height: { type: 'number', min: 0.12, max: 1.4, default: 0.34 },
      radius: { type: 'number', min: 0.035, max: 0.5, default: 0.095 },
      rollerLength: { type: 'number', min: 0.08, max: 1.2, default: 0.28 },
      metalColor: { type: 'color', default: '#64748b' },
      rollerColor: { type: 'color', default: '#374151' },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'tank.motor_gearbox_unit',
    family: 'tank',
    kind: 'motor_gearbox_unit',
    semanticRole: 'drive_unit',
    aliases: ['motor_gearbox_unit', 'drive_unit', 'gearmotor', 'motor_reducer_unit'],
    attachTo: 'cylindrical_tank',
    layoutRole: 'side_drive_unit',
    description: 'Compact side drive with motor, gearbox housing, and output shaft.',
    params: {
      length: { type: 'number', min: 0.3, max: 4, default: 1.05 },
      height: { type: 'number', min: 0.12, max: 1.8, default: 0.38 },
      radius: { type: 'number', min: 0.05, max: 0.8, default: 0.18 },
      primaryColor: { type: 'color', default: '#64748b' },
      secondaryColor: { type: 'color', default: '#475569' },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'tank.coupling_guard',
    family: 'tank',
    kind: 'coupling_guard',
    semanticRole: 'coupling_guard',
    aliases: ['coupling_guard', 'shaft_guard', 'coupling_cover'],
    attachTo: 'motor_gearbox_unit',
    layoutRole: 'drive_guard',
    description: 'Half-cylinder safety guard over a drive coupling.',
    params: {
      length: { type: 'number', min: 0.16, max: 2.4, default: 0.58 },
      radius: { type: 'number', min: 0.04, max: 0.7, default: 0.16 },
      thickness: { type: 'number', min: 0.006, max: 0.16, default: 0.028 },
      color: { type: 'color', default: '#facc15' },
      darkColor: { type: 'color', default: '#111827' },
    },
  },
  {
    id: 'tank.hopper_body',
    family: 'tank',
    kind: 'hopper_body',
    semanticRole: 'hopper_body',
    aliases: ['hopper_body', 'feed_hopper', 'inlet_hopper', 'discharge_hopper'],
    attachTo: 'cylindrical_tank',
    layoutRole: 'feed_hopper',
    description: 'Tapered feed or discharge hopper attached to process vessels.',
    params: {
      length: { type: 'number', min: 0.12, max: 3, default: 0.65 },
      width: { type: 'number', min: 0.12, max: 3, default: 0.48 },
      height: { type: 'number', min: 0.12, max: 3, default: 0.72 },
      primaryColor: { type: 'color', default: '#94a3b8' },
      metalColor: { type: 'color', default: '#64748b' },
    },
  },
  {
    id: 'tank.service_platform',
    family: 'tank',
    kind: 'service_platform',
    semanticRole: 'service_platform',
    aliases: ['service_platform', 'inspection_platform', 'maintenance_platform', 'guard_rail'],
    attachTo: 'cylindrical_tank',
    layoutRole: 'access_platform',
    description: 'Service platform with support posts, guard rails, and access ladder.',
    params: {
      length: { type: 'number', min: 0.3, max: 8, default: 1.4 },
      width: { type: 'number', min: 0.16, max: 2, default: 0.42 },
      height: { type: 'number', min: 0.08, max: 3, default: 0.75 },
      overallHeight: { type: 'number', min: 0.08, max: 3, default: 0.45 },
      detailLevel: { type: 'enum', values: ['low', 'medium', 'high'], default: 'medium' },
      metalColor: { type: 'color', default: '#64748b' },
      color: { type: 'color', default: '#facc15' },
    },
  },
  {
    id: 'tank.inlet_port',
    family: 'tank',
    kind: 'inlet_port',
    aliases: ['inlet', 'feed_nozzle', 'tank_inlet', 'top_nozzle', '入口', '进料口'],
    attachTo: 'cylindrical_tank',
    layoutRole: 'top_nozzle',
    description: 'Tank inlet / feed nozzle.',
    params: {
      radius: { type: 'number', min: 0.01, max: 1, default: 0.08 },
      length: { type: 'number', min: 0.03, max: 2, default: 0.22 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'y' },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'tank.outlet_port',
    family: 'tank',
    kind: 'outlet_port',
    aliases: ['outlet', 'drain_nozzle', 'tank_outlet', 'bottom_nozzle', '出口', '排出口'],
    attachTo: 'cylindrical_tank',
    layoutRole: 'side_drain_nozzle',
    description: 'Tank outlet / drain nozzle.',
    params: {
      radius: { type: 'number', min: 0.01, max: 1, default: 0.07 },
      length: { type: 'number', min: 0.03, max: 2, default: 0.22 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'x' },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'tank.platform_ladder',
    family: 'tank',
    kind: 'platform_ladder',
    semanticRole: 'access_platform',
    aliases: ['ladder', 'platform', 'access_platform', 'guard_platform', '爬梯', '平台'],
    attachTo: 'cylindrical_tank',
    layoutRole: 'side_access',
    description: 'Access platform and ladder for tank inspection.',
    params: {
      length: { type: 'number', min: 0.12, max: 4, default: 0.72 },
      width: { type: 'number', min: 0.12, max: 3, default: 0.48 },
      height: { type: 'number', min: 0.2, max: 6, default: 1.2 },
      radius: { type: 'number', min: 0.004, max: 0.08, default: 0.018 },
      detailLevel: { type: 'enum', values: ['low', 'medium', 'high'], default: 'medium' },
      rungCount: { type: 'integer', min: 4, max: 16, default: 6 },
      metalColor: { type: 'color', default: '#94a3b8' },
    },
  },
  {
    id: 'tank.pipe_manifold',
    family: 'tank',
    kind: 'pipe_manifold',
    semanticRole: 'pipe_manifold',
    aliases: ['pipe_manifold', 'manifold', 'header_pipe', 'cooling_water_header'],
    attachTo: 'cooling_tower_shell',
    layoutRole: 'cooling_water_header',
    description: 'Process pipe manifold or cooling-water header for vessel and tower groups.',
    params: {
      length: { type: 'number', min: 0.25, max: 12, default: 1.2 },
      radius: { type: 'number', min: 0.012, max: 0.4, default: 0.065 },
      count: { type: 'integer', min: 2, max: 10, default: 4 },
      metalColor: { type: 'color', default: '#94a3b8' },
    },
  },
]

export const REACTOR_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'reactor.agitator_tank',
    family: 'reactor',
    kind: 'agitator_tank',
    aliases: ['reactor', 'reaction_kettle', 'stirred_tank', 'agitator_tank', '反应釜', '搅拌罐'],
    required: true,
    layoutRole: 'stirred_vessel',
    description: 'Stirred reactor vessel with agitator motor, shaft, and impeller blades.',
    params: {
      height: { type: 'number', min: 0.2, max: 5, default: 1.4 },
      radius: { type: 'number', min: 0.06, max: 2, default: 0.42 },
      bottomStyle: { type: 'enum', values: ['dished', 'conical'], default: 'dished' },
      legStyle: { type: 'enum', values: ['vertical', 'splayed'], default: 'vertical' },
      legCount: { type: 'integer', min: 3, max: 4, default: 4 },
      primaryColor: { type: 'color', default: '#94a3b8' },
      metalColor: { type: 'color', default: '#cbd5e1' },
      motorColor: { type: 'color', default: '#1f2937' },
    },
  },
  {
    id: 'reactor.inlet_port',
    family: 'reactor',
    kind: 'inlet_port',
    aliases: ['inlet', 'feed_nozzle', 'reactor_inlet', '进料口', '入口'],
    required: true,
    attachTo: 'agitator_tank',
    layoutRole: 'feed_nozzle',
    description: 'Reactor feed inlet nozzle.',
    params: {
      radius: { type: 'number', min: 0.01, max: 0.8, default: 0.06 },
      length: { type: 'number', min: 0.03, max: 1.5, default: 0.18 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'y' },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'reactor.outlet_port',
    family: 'reactor',
    kind: 'outlet_port',
    aliases: ['outlet', 'discharge_nozzle', 'reactor_outlet', '出料口', '出口'],
    required: true,
    attachTo: 'agitator_tank',
    layoutRole: 'discharge_nozzle',
    description: 'Reactor discharge outlet nozzle.',
    params: {
      radius: { type: 'number', min: 0.01, max: 0.8, default: 0.055 },
      length: { type: 'number', min: 0.03, max: 1.5, default: 0.18 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'x' },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'reactor.mixer_blades',
    family: 'reactor',
    kind: 'mixer_blades',
    semanticRole: 'reactor_impeller',
    aliases: ['mixer_blades', 'agitator_blade', 'impeller_blade', 'paddle', 'blade'],
    attachTo: 'agitator_tank',
    layoutRole: 'internal_impeller',
    description: 'Reactor agitator / mixer impeller blades.',
    params: {
      count: { type: 'integer', min: 2, max: 8, default: 3 },
      length: { type: 'number', min: 0.04, max: 2, default: 0.32 },
      width: { type: 'number', min: 0.02, max: 1, default: 0.12 },
      depth: { type: 'number', min: 0.004, max: 0.2, default: 0.018 },
      bladePitch: { type: 'number', min: -1, max: 1, default: 0.22 },
      curvature: { type: 'number', min: 0, max: 0.5, default: 0.08 },
      primaryColor: { type: 'color', default: '#cbd5e1' },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'reactor.platform_ladder',
    family: 'reactor',
    kind: 'platform_ladder',
    semanticRole: 'access_platform',
    aliases: ['ladder', 'platform', 'access_platform', '爬梯', '平台'],
    attachTo: 'agitator_tank',
    layoutRole: 'side_access',
    description: 'Reactor access platform and ladder.',
    params: {
      length: { type: 'number', min: 0.12, max: 4, default: 0.72 },
      width: { type: 'number', min: 0.12, max: 3, default: 0.48 },
      height: { type: 'number', min: 0.2, max: 6, default: 1.2 },
      radius: { type: 'number', min: 0.004, max: 0.08, default: 0.018 },
      detailLevel: { type: 'enum', values: ['low', 'medium', 'high'], default: 'medium' },
      rungCount: { type: 'integer', min: 4, max: 16, default: 6 },
      metalColor: { type: 'color', default: '#94a3b8' },
    },
  },
]

export const COMPRESSOR_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'compressor.skid_base',
    family: 'compressor',
    kind: 'skid_base',
    semanticRole: 'machine_base',
    aliases: ['base', 'skid', 'compressor_base', '底座'],
    required: true,
    layoutRole: 'machine_skid',
    description: 'Compressor skid base.',
    params: {
      length: { type: 'number', min: 0.3, max: 8, default: 1.8 },
      width: { type: 'number', min: 0.12, max: 4, default: 0.7 },
      height: { type: 'number', min: 0.02, max: 1, default: 0.12 },
      metalColor: { type: 'color', default: '#64748b' },
    },
  },
  {
    id: 'compressor.ribbed_motor_body',
    family: 'compressor',
    kind: 'ribbed_motor_body',
    semanticRole: 'motor_body',
    aliases: ['motor', 'drive_motor', 'electric_motor', '电机'],
    required: true,
    attachTo: 'skid_base',
    layoutRole: 'drive_motor',
    description: 'Ribbed electric drive motor.',
    params: {
      length: { type: 'number', min: 0.12, max: 3, default: 0.55 },
      radius: { type: 'number', min: 0.04, max: 1, default: 0.18 },
      slatCount: { type: 'integer', min: 3, max: 20, default: 8 },
      primaryColor: { type: 'color', default: '#64748b' },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'compressor.rounded_machine_body',
    family: 'compressor',
    kind: 'rounded_machine_body',
    semanticRole: 'compressor_casing',
    aliases: ['compressor_casing', 'compressor_body', 'casing', '压缩机壳体'],
    required: true,
    attachTo: 'skid_base',
    layoutRole: 'compressor_casing',
    description: 'Rounded compressor casing.',
    params: {
      length: { type: 'number', min: 0.12, max: 4, default: 0.58 },
      width: { type: 'number', min: 0.08, max: 2, default: 0.36 },
      height: { type: 'number', min: 0.08, max: 2, default: 0.36 },
      primaryColor: { type: 'color', default: '#64748b' },
    },
  },
  {
    id: 'compressor.inlet_port',
    family: 'compressor',
    kind: 'inlet_port',
    aliases: ['inlet', 'suction', 'air_inlet', '入口', '进气口'],
    required: true,
    attachTo: 'rounded_machine_body',
    layoutRole: 'suction_port',
    description: 'Compressor inlet port.',
    params: {
      radius: { type: 'number', min: 0.01, max: 0.8, default: 0.07 },
      length: { type: 'number', min: 0.03, max: 1.5, default: 0.2 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'x' },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'compressor.outlet_port',
    family: 'compressor',
    kind: 'outlet_port',
    aliases: ['outlet', 'discharge', 'air_outlet', '出口', '排气口'],
    required: true,
    attachTo: 'rounded_machine_body',
    layoutRole: 'discharge_port',
    description: 'Compressor discharge outlet port.',
    params: {
      radius: { type: 'number', min: 0.01, max: 0.8, default: 0.06 },
      length: { type: 'number', min: 0.03, max: 1.5, default: 0.2 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'x' },
      metalColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'compressor.control_box',
    family: 'compressor',
    kind: 'control_box',
    semanticRole: 'control_box',
    aliases: ['control_box', 'controller', 'control_panel', '控制盒'],
    attachTo: 'skid_base',
    layoutRole: 'side_controller',
    description: 'Compressor control box.',
    params: {
      length: { type: 'number', min: 0.04, max: 1.2, default: 0.2 },
      width: { type: 'number', min: 0.03, max: 1, default: 0.14 },
      height: { type: 'number', min: 0.03, max: 1, default: 0.12 },
      primaryColor: { type: 'color', default: '#1f2937' },
    },
  },
]

export const HEAT_EXCHANGER_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'heat_exchanger.heat_exchanger',
    family: 'heat_exchanger',
    kind: 'heat_exchanger',
    aliases: ['heat_exchanger', 'condenser', 'cooler', 'shell_and_tube', '换热器', '冷凝器'],
    required: true,
    layoutRole: 'shell_and_tube_bundle',
    description: 'Shell-and-tube heat exchanger body with channel heads and nozzles.',
    params: {
      length: { type: 'number', min: 0.24, max: 8, default: 1.6 },
      radius: { type: 'number', min: 0.05, max: 1.5, default: 0.24 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'x' },
      primaryColor: { type: 'color', default: '#9ca3af' },
    },
  },
  {
    id: 'heat_exchanger.skid_base',
    family: 'heat_exchanger',
    kind: 'skid_base',
    semanticRole: 'support_base',
    aliases: ['support', 'saddle', 'base', 'skid', '支座'],
    attachTo: 'heat_exchanger',
    layoutRole: 'support_saddles',
    description: 'Heat exchanger support base.',
    params: {
      length: { type: 'number', min: 0.2, max: 8, default: 1.4 },
      width: { type: 'number', min: 0.08, max: 3, default: 0.48 },
      height: { type: 'number', min: 0.02, max: 1, default: 0.1 },
      metalColor: { type: 'color', default: '#64748b' },
    },
  },
]

export const MACHINE_TOOL_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'machine_tool.generic_base',
    family: 'machine_tool',
    kind: 'generic_base',
    semanticRole: 'machine_base',
    aliases: ['base', 'machine_base', 'bed', 'lathe_bed', '床身', '底座'],
    required: true,
    layoutRole: 'machine_bed',
    description: 'Machine tool base / bed.',
    params: {
      length: { type: 'number', min: 0.4, max: 10, default: 2.4 },
      width: { type: 'number', min: 0.18, max: 5, default: 1.0 },
      thickness: { type: 'number', min: 0.03, max: 1, default: 0.16 },
      darkColor: { type: 'color', default: '#1f2937' },
    },
  },
  {
    id: 'machine_tool.generic_body',
    family: 'machine_tool',
    kind: 'generic_body',
    semanticRole: 'machine_enclosure',
    aliases: ['enclosure', 'machine_body', 'cnc_enclosure', 'housing', '机床外壳'],
    required: true,
    attachTo: 'generic_base',
    layoutRole: 'machine_enclosure',
    description: 'Machine tool enclosure / main body.',
    params: {
      length: { type: 'number', min: 0.3, max: 8, default: 1.7 },
      width: { type: 'number', min: 0.16, max: 4, default: 0.8 },
      height: { type: 'number', min: 0.2, max: 4, default: 1.2 },
      primaryColor: { type: 'color', default: '#94a3b8' },
    },
  },
  {
    id: 'machine_tool.generic_panel',
    family: 'machine_tool',
    kind: 'generic_panel',
    semanticRole: 'spindle_head',
    aliases: ['spindle', 'spindle_head', 'tool_head', '主轴', '主轴头'],
    required: true,
    attachTo: 'generic_body',
    layoutRole: 'front_spindle_head',
    description: 'Spindle head or tool head panel.',
    params: {
      length: { type: 'number', min: 0.05, max: 3, default: 0.45 },
      height: { type: 'number', min: 0.05, max: 2, default: 0.36 },
      thickness: { type: 'number', min: 0.004, max: 0.4, default: 0.05 },
      color: { type: 'color', default: '#334155' },
    },
  },
  {
    id: 'machine_tool.viewing_panel',
    family: 'machine_tool',
    kind: 'generic_panel',
    semanticRole: 'viewing_panel',
    aliases: [
      'viewing_panel',
      'viewing_window',
      'observation_window',
      'front_window',
      'transparent_panel',
      'window',
      'glass',
      'inspection_window',
    ],
    attachTo: 'generic_body',
    layoutRole: 'front_viewing_window',
    description: 'Transparent front viewing window for an enclosed CNC machine.',
    params: {
      length: { type: 'number', min: 0.05, max: 4, default: 0.9 },
      height: { type: 'number', min: 0.05, max: 2.5, default: 0.65 },
      thickness: { type: 'number', min: 0.003, max: 0.16, default: 0.012 },
      color: { type: 'color', default: '#88CCEE' },
      opacity: { type: 'number', min: 0.1, max: 1, default: 0.48 },
    },
  },
  {
    id: 'machine_tool.work_table',
    family: 'machine_tool',
    kind: 'generic_panel',
    semanticRole: 'work_table',
    aliases: ['work_table', 'machine_table', 'fixture_table', 'bed_table', '工作台'],
    attachTo: 'generic_body',
    layoutRole: 'inside_work_table',
    description: 'Internal work table or fixture table below the spindle.',
    params: {
      length: { type: 'number', min: 0.08, max: 5, default: 1.0 },
      width: { type: 'number', min: 0.04, max: 3, default: 0.65 },
      thickness: { type: 'number', min: 0.01, max: 0.4, default: 0.06 },
      color: { type: 'color', default: '#555566' },
    },
  },
  {
    id: 'machine_tool.feed_chute',
    family: 'machine_tool',
    kind: 'generic_spout',
    semanticRole: 'feed_chute',
    aliases: ['feed_chute', 'feed_hopper', 'infeed', 'infeed_chute', 'material_inlet'],
    attachTo: 'generic_body',
    layoutRole: 'front_feed_chute',
    description: 'Feed chute, hopper, or material inlet for enclosed production machinery.',
    params: {
      length: { type: 'number', min: 0.04, max: 2, default: 0.34 },
      radius: { type: 'number', min: 0.008, max: 0.35, default: 0.08 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'z' },
      darkColor: { type: 'color', default: '#374151' },
    },
  },
  {
    id: 'machine_tool.discharge_chute',
    family: 'machine_tool',
    kind: 'generic_spout',
    semanticRole: 'discharge_chute',
    aliases: ['discharge_chute', 'outfeed', 'outfeed_chute', 'material_outlet', 'product_exit'],
    attachTo: 'generic_body',
    layoutRole: 'rear_discharge_chute',
    description: 'Discharge chute or product outlet for enclosed production machinery.',
    params: {
      length: { type: 'number', min: 0.04, max: 2, default: 0.4 },
      radius: { type: 'number', min: 0.008, max: 0.35, default: 0.09 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'z' },
      darkColor: { type: 'color', default: '#374151' },
    },
  },
  {
    id: 'machine_tool.control_box',
    family: 'machine_tool',
    kind: 'control_box',
    semanticRole: 'control_panel',
    aliases: ['control_panel', 'control_box', 'operator_panel', '控制面板'],
    required: true,
    attachTo: 'generic_body',
    layoutRole: 'operator_panel',
    description: 'Operator control panel / pendant.',
    params: {
      length: { type: 'number', min: 0.04, max: 1.5, default: 0.28 },
      width: { type: 'number', min: 0.03, max: 1, default: 0.16 },
      height: { type: 'number', min: 0.03, max: 1.2, default: 0.36 },
      primaryColor: { type: 'color', default: '#1f2937' },
    },
  },
  {
    id: 'machine_tool.spindle_nose',
    family: 'machine_tool',
    kind: 'generic_spout',
    semanticRole: 'spindle_nose',
    aliases: ['spindle_nose', 'spindle_spout', 'tool_nose', 'tool_tip', 'cutter_nose'],
    attachTo: 'generic_panel',
    layoutRole: 'below_spindle_head',
    description: 'Short spindle nose or tool tip below the spindle head.',
    params: {
      length: { type: 'number', min: 0.03, max: 0.6, default: 0.14 },
      radius: { type: 'number', min: 0.008, max: 0.2, default: 0.04 },
      darkColor: { type: 'color', default: '#18181B' },
    },
  },
  {
    id: 'machine_tool.display_screen',
    family: 'machine_tool',
    kind: 'generic_display',
    semanticRole: 'display_screen',
    aliases: ['display', 'screen', 'display_screen', 'operator_screen', 'hmi_screen'],
    attachTo: 'control_box',
    layoutRole: 'control_panel_screen',
    description: 'Operator HMI screen on the control panel.',
    params: {
      length: { type: 'number', min: 0.03, max: 1, default: 0.26 },
      height: { type: 'number', min: 0.02, max: 0.8, default: 0.18 },
      thickness: { type: 'number', min: 0.002, max: 0.08, default: 0.008 },
      color: { type: 'color', default: '#1A1A2E' },
    },
  },
  {
    id: 'machine_tool.vent_panel',
    family: 'machine_tool',
    kind: 'vent_slats',
    semanticRole: 'vent_panel',
    aliases: ['vent', 'vents', 'vent_panel', 'vent_slats', 'louver', 'louvers', 'cooling_vent'],
    attachTo: 'generic_body',
    layoutRole: 'side_vent_panel',
    description: 'Side ventilation slats for heat dissipation.',
    params: {
      length: { type: 'number', min: 0.06, max: 3, default: 0.48 },
      height: { type: 'number', min: 0.04, max: 2, default: 0.48 },
      thickness: { type: 'number', min: 0.004, max: 0.12, default: 0.02 },
      detailLevel: { type: 'enum', values: ['low', 'medium', 'high'], default: 'medium' },
      slatCount: { type: 'integer', min: 2, max: 18, default: 6 },
      color: { type: 'color', default: '#475569' },
    },
  },
  {
    id: 'machine_tool.access_panel',
    family: 'machine_tool',
    kind: 'generic_detail_accent',
    semanticRole: 'access_panel',
    aliases: [
      'access_panel',
      'maintenance_panel',
      'inspection_panel',
      'service_panel',
      'door_panel',
    ],
    attachTo: 'generic_body',
    layoutRole: 'side_access_panel',
    required: true,
    description: 'Maintenance or inspection access panel on the machine enclosure.',
    params: {
      length: { type: 'number', min: 0.05, max: 3, default: 0.65 },
      height: { type: 'number', min: 0.04, max: 2, default: 0.45 },
      thickness: { type: 'number', min: 0.003, max: 0.12, default: 0.015 },
      accentColor: { type: 'color', default: '#666677' },
    },
  },
  {
    id: 'machine_tool.warning_label',
    family: 'machine_tool',
    kind: 'warning_label',
    semanticRole: 'warning_label',
    aliases: ['warning', 'warning_label', 'safety_label', 'hazard_label'],
    attachTo: 'generic_body',
    layoutRole: 'front_warning_label',
    description: 'Small safety warning label on the front enclosure.',
    params: {
      length: { type: 'number', min: 0.03, max: 0.8, default: 0.16 },
      height: { type: 'number', min: 0.02, max: 0.5, default: 0.08 },
      thickness: { type: 'number', min: 0.001, max: 0.04, default: 0.004 },
    },
  },
  {
    id: 'machine_tool.nameplate',
    family: 'machine_tool',
    kind: 'nameplate',
    semanticRole: 'nameplate',
    aliases: ['nameplate', 'brand_plate', 'manufacturer_plate', '铭牌'],
    attachTo: 'generic_body',
    layoutRole: 'front_nameplate',
    description: 'Manufacturer nameplate or model plate.',
    params: {
      length: { type: 'number', min: 0.03, max: 0.9, default: 0.2 },
      height: { type: 'number', min: 0.02, max: 0.45, default: 0.06 },
      thickness: { type: 'number', min: 0.001, max: 0.04, default: 0.004 },
    },
  },
]

export const OUTDOOR_AC_PART_DEFINITIONS: readonly PartDefinition[] = [
  {
    id: 'outdoor_ac.rounded_machine_body',
    family: 'outdoor_ac',
    kind: 'rounded_machine_body',
    semanticRole: 'outdoor_ac_body',
    aliases: [
      'outdoor_ac_body',
      'condenser_body',
      'casing',
      'cabinet',
      'enclosure',
      'machine_body',
    ],
    required: true,
    layoutRole: 'enclosure',
    description: 'Rounded rectangular outdoor AC condenser enclosure.',
    params: {
      length: { type: 'number', min: 0.12, max: 4, default: 0.86 },
      width: { type: 'number', min: 0.08, max: 2, default: 0.34 },
      height: { type: 'number', min: 0.08, max: 2.4, default: 0.62 },
      primaryColor: { type: 'color', default: '#8b9aae' },
    },
  },
  {
    id: 'outdoor_ac.vent_grill',
    family: 'outdoor_ac',
    kind: 'vent_grill',
    semanticRole: 'front_vent',
    aliases: [
      'vent_grill',
      'vent_grille',
      'front_vent',
      'front_grille',
      'fan_exhaust',
      'air_grille',
      'louver_grill',
    ],
    required: true,
    attachTo: 'rounded_machine_body',
    layoutRole: 'front_vent',
    description: 'Front louver grille on the condenser casing.',
    params: {
      length: { type: 'number', min: 0.04, max: 3, default: 0.56 },
      width: { type: 'number', min: 0.01, max: 0.5, default: 0.04 },
      height: { type: 'number', min: 0.01, max: 1.5, default: 0.3 },
      slatCount: { type: 'integer', min: 2, max: 20, default: 8 },
      primaryColor: { type: 'color', default: '#cbd5e1' },
    },
  },
  {
    id: 'outdoor_ac.radial_blades',
    family: 'outdoor_ac',
    kind: 'radial_blades',
    semanticRole: 'fan_impeller',
    aliases: [
      'radial_blades',
      'fan_blades',
      'fan_impeller',
      'condenser_fan',
      'axial_fan',
      'impeller',
    ],
    required: true,
    attachTo: 'vent_grill',
    layoutRole: 'front_fan',
    description: 'Visible condenser fan blades behind or within the front grille.',
    params: {
      count: { type: 'integer', min: 2, max: 8, default: 4 },
      bladeRadius: { type: 'number', min: 0.04, max: 1.2, default: 0.24 },
      bladeWidth: { type: 'number', min: 0.01, max: 0.5, default: 0.06 },
      bladePitch: { type: 'number', min: -0.65, max: 0.65, default: 0.24 },
      primaryColor: { type: 'color', default: '#94a3b8' },
    },
  },
  {
    id: 'outdoor_ac.pipe_port',
    family: 'outdoor_ac',
    kind: 'pipe_port',
    semanticRole: 'refrigerant_port',
    aliases: [
      'pipe_port',
      'refrigerant_port',
      'refrigerant_inlet',
      'refrigerant_outlet',
      'service_port',
      'connection_pipe',
    ],
    attachTo: 'rounded_machine_body',
    layoutRole: 'side_pipe_port',
    description: 'Small refrigerant pipe connection on the side of the condenser unit.',
    params: {
      radius: { type: 'number', min: 0.004, max: 0.18, default: 0.024 },
      length: { type: 'number', min: 0.02, max: 1, default: 0.12 },
      axis: { type: 'enum', values: ['x', 'y', 'z'], default: 'x' },
      metalColor: { type: 'color', default: '#94a3b8' },
    },
  },
  {
    id: 'outdoor_ac.nameplate',
    family: 'outdoor_ac',
    kind: 'nameplate',
    semanticRole: 'unit_label',
    aliases: ['nameplate', 'unit_label', 'brand_plate', 'manufacturer_plate'],
    attachTo: 'rounded_machine_body',
    layoutRole: 'front_nameplate',
    description: 'Small front nameplate label.',
    params: {
      length: { type: 'number', min: 0.03, max: 0.9, default: 0.18 },
      height: { type: 'number', min: 0.02, max: 0.45, default: 0.06 },
      thickness: { type: 'number', min: 0.001, max: 0.04, default: 0.004 },
    },
  },
  {
    id: 'outdoor_ac.warning_label',
    family: 'outdoor_ac',
    kind: 'warning_label',
    semanticRole: 'warning_label',
    aliases: ['warning_label', 'warning_sticker', 'safety_label'],
    attachTo: 'rounded_machine_body',
    layoutRole: 'front_warning_label',
    description: 'Small safety warning label.',
    params: {
      length: { type: 'number', min: 0.03, max: 0.9, default: 0.16 },
      height: { type: 'number', min: 0.02, max: 0.45, default: 0.05 },
      thickness: { type: 'number', min: 0.001, max: 0.04, default: 0.004 },
    },
  },
]
