import type { PartComposeKind, PartComposePartInput } from './types'

export function normalizePartKind(kind: unknown): PartComposeKind | null {
  const raw =
    typeof kind === 'string'
      ? kind
          .trim()
          .toLowerCase()
          .replace(/[\s-]+/g, '_')
      : ''
  switch (raw) {
    case 'base':
    case 'round_base':
    case 'circular_base':
      return 'circular_base'
    case 'pole':
    case 'rod':
    case 'vertical_pole':
      return 'vertical_pole'
    case 'motor':
    case 'motor_housing':
    case 'head_housing':
      return 'motor_housing'
    case 'blades':
    case 'blade':
    case 'fan_blade':
    case 'fanblade':
    case 'impeller_fan_blade':
      return 'fan_blade'
    case 'fan_blades':
    case 'radial_blades':
      return 'radial_blades'
    case 'grill':
    case 'grille':
    case 'cage':
    case 'protective_grill':
    case 'protective_grille':
      return 'protective_grill'
    case 'pyramid':
    case 'square_pyramid':
    case 'four_sided_pyramid':
    case 'tetra_pyramid':
      return 'pyramid'
    case 'hemisphere':
    case 'half_sphere':
    case 'semi_sphere':
    case 'dome':
    case 'half_dome':
    case '\u534a\u7403':
    case '\u534a\u7403\u4f53':
    case '\u534a\u5706\u7403':
    case '\u534a\u5706\u5f62\u7403':
      return 'hemisphere'
    case 'bracket':
    case 'yoke':
    case 'support_bracket':
      return 'support_bracket'
    case 'knob':
    case 'control_knob':
      return 'control_knob'
    case 'vents':
    case 'slats':
    case 'louvers':
    case 'louver':
    case 'louver_panel':
    case 'louvered_panel':
    case 'louvered_vents':
    case 'vent_slats':
      return 'vent_slats'
    case 'vent_grill':
    case 'vent_grille':
    case 'grille_panel':
    case 'air_grille':
    case 'louver_grill':
    case 'louvered_grill':
    case 'air_vent_grill':
      return 'vent_grill'
    case 'skid':
    case 'skid_base':
    case 'machine_base':
    case 'base_frame':
      return 'skid_base'
    case 'body':
    case 'machine_body':
    case 'rounded_body':
    case 'rounded_machine_body':
      return 'rounded_machine_body'
    case 'volute':
    case 'volute_casing':
    case 'pump_casing':
    case 'blower_casing':
    case 'scroll_casing':
      return 'volute_casing'
    case 'impeller':
    case 'impeller_blades':
    case 'pump_impeller':
    case 'turbine_blades':
      return 'impeller_blades'
    case 'propeller_blade_set':
    case 'propeller_blades':
    case 'propeller_set':
    case 'blade_set':
    case 'paddle_set':
    case 'agitator_blade_set':
    case 'taiji_propeller':
    case 'taiji_half_blades':
      return 'propeller_blade_set'
    case 'mixer_blades':
    case 'mixer_impeller':
    case 'mud_mixer_blades':
    case 'agitator_blades':
    case 'taiji_blades':
      return 'mixer_blades'
    case 'wheel':
    case 'single_wheel':
    case 'rubber_wheel':
    case 'landing_wheel':
    case 'bicycle_wheel':
    case 'bike_wheel':
    case 'cycle_wheel':
    case 'front_bicycle_wheel':
    case 'rear_bicycle_wheel':
      return 'wheel'
    case 'wheel_set':
    case 'wheels':
    case 'wheelset':
    case 'wheel_pair':
    case 'tire_set':
    case 'tire_pair':
      return 'wheel_set'
    case 'window_panel':
    case 'glass_panel':
    case 'rounded_window':
    case 'window':
      return 'window_panel'
    case 'window_strip':
    case 'glass_strip':
    case 'window_array':
    case 'cabin_windows':
      return 'window_strip'
    case 'body_shell':
    case 'shell_body':
    case 'vehicle_body':
    case 'car_body':
    case 'auto_body':
      return 'body_shell'
    case 'tube_frame':
    case 'frame_assembly':
    case 'bicycle_frame':
    case 'bike_frame':
    case 'bicycle':
    case 'bike':
    case 'complete_bicycle':
    case 'complete_bike':
      return 'tube_frame'
    case 'fork':
    case 'bicycle_fork':
    case 'front_fork':
    case 'bike_fork':
      return 'fork'
    case 'light_pair':
    case 'headlights':
    case 'head_lights':
    case 'lamps':
      return 'light_pair'
    case 'bar_pair':
    case 'bumper':
    case 'bumpers':
    case 'car_bumper':
      return 'bar_pair'
    case 'generic_body':
    case 'generic_main_body':
    case 'main_body':
    case 'equipment_body':
    case 'building_body':
    case 'furniture_body':
    case 'cabinet_body':
    case 'housing':
    case 'shell':
      return 'generic_body'
    case 'generic_base':
    case 'support_base':
    case 'platform_base':
    case 'base_slab':
    case 'cup_platform':
    case 'generic_platform':
      return 'generic_base'
    case 'generic_panel':
    case 'panel':
    case 'front_panel':
    case 'side_panel':
    case 'access_panel':
      return 'generic_panel'
    case 'generic_handle':
    case 'handle':
    case 'pull_handle':
    case 'door_handle':
      return 'generic_handle'
    case 'generic_spout':
    case 'spout':
    case 'nozzle_spout':
    case 'coffee_spout':
    case 'dispense_spout':
      return 'generic_spout'
    case 'generic_control_panel':
    case 'control_detail':
    case 'buttons':
    case 'button_panel':
      return 'generic_control_panel'
    case 'generic_display':
    case 'display':
    case 'screen':
    case 'readout':
      return 'generic_display'
    case 'generic_foot_set':
    case 'foot_set':
      return 'generic_foot_set'
    case 'generic_opening':
    case 'opening':
    case 'door_opening':
    case 'window_opening':
      return 'generic_opening'
    case 'generic_detail_accent':
    case 'detail_accent':
    case 'accent':
    case 'trim':
      return 'generic_detail_accent'
    case 'mobile_platform_chassis':
    case 'mobile_chassis':
    case 'agv_chassis':
    case 'amr_chassis':
    case 'robot_platform_chassis':
      return 'mobile_platform_chassis'
    case 'lidar_sensor':
    case 'laser_scanner':
    case 'navigation_sensor':
    case 'safety_scanner':
    case 'scanner':
      return 'lidar_sensor'
    case 'emergency_stop_button':
    case 'e_stop':
    case 'e_stop_button':
    case 'emergency_button':
    case 'stop_button':
      return 'emergency_stop_button'
    case 'status_light_strip':
    case 'light_strip':
    case 'led_strip':
    case 'signal_light_strip':
    case 'status_strip':
      return 'status_light_strip'
    case 'operator_panel':
    case 'hmi_panel':
    case 'control_pendant':
    case 'operator_console':
      return 'operator_panel'
    case 'guard_fence':
    case 'safety_fence':
    case 'safety_guard':
    case 'guard_rail':
    case 'barrier_fence':
      return 'guard_fence'
    case 'pallet_table':
    case 'pallet_station':
    case 'pallet_deck':
    case 'fixture_table':
      return 'pallet_table'
    case 'bearing_block':
    case 'pillow_block':
    case 'pillow_block_bearing':
    case 'bearing_housing':
    case 'mounted_bearing':
      return 'bearing_block'
    case 'coupling_guard':
    case 'shaft_guard':
    case 'coupling_cover':
    case 'rotating_shaft_guard':
      return 'coupling_guard'
    case 'motor_gearbox_unit':
    case 'motor_reducer_unit':
    case 'drive_unit':
    case 'gearmotor':
    case 'motor_gearbox':
      return 'motor_gearbox_unit'
    case 'pipe_manifold':
    case 'manifold':
    case 'header_pipe':
    case 'branch_manifold':
      return 'pipe_manifold'
    case 'hopper_body':
    case 'feed_hopper':
    case 'material_hopper':
    case 'inlet_hopper':
      return 'hopper_body'
    case 'conical_hopper':
    case 'cone_hopper':
    case 'cone_discharge_hopper':
      return 'conical_hopper'
    case 'service_platform':
    case 'maintenance_platform':
    case 'inspection_platform':
    case 'access_deck':
      return 'service_platform'
    case 'platform_with_ladder':
    case 'maintenance_platform_ladder':
    case 'access_platform_ladder':
      return 'platform_with_ladder'
    case 'kiosk_body':
    case 'booth_body':
    case 'small_building_body':
    case 'stall_body':
    case 'newsstand_body':
      return 'kiosk_body'
    case 'kiosk_roof':
    case 'booth_roof':
    case 'small_building_roof':
    case 'pavilion_roof':
    case 'shed_roof':
      return 'kiosk_roof'
    case 'kiosk_opening':
    case 'service_window':
    case 'serving_window':
    case 'ticket_window':
    case 'booth_window':
    case 'kiosk_door':
      return 'kiosk_opening'
    case 'kiosk_counter':
    case 'service_counter':
    case 'serving_counter':
    case 'sales_counter':
    case 'vendor_counter':
      return 'kiosk_counter'
    case 'kiosk_sign':
    case 'sign_panel':
    case 'shop_sign':
    case 'booth_sign':
    case 'name_sign':
      return 'kiosk_sign'
    case 'kiosk_awning':
    case 'awning':
    case 'canopy':
    case 'sunshade':
      return 'kiosk_awning'
    case 'airfoil_blade':
    case 'airfoil_blades':
    case 'propeller_blade':
    case 'turbine_blade':
    case 'curved_blade':
    case 'curved_blades':
      return 'airfoil_blade'
    case 'ellipsoid_shell':
    case 'ellipsoidal_shell':
    case 'elliptical_shell':
    case 'oval_shell':
    case 'dome_shell':
    case 'equipment_dome':
    case 'helmet_shell':
    case 'mouse_dome':
    case 'tank_head':
    case 'vessel_head':
      return 'ellipsoid_shell'
    case 'curved_lens':
    case 'curved_panel':
    case 'arc_panel':
    case 'bent_panel':
    case 'curved_lens_panel':
    case 'lens_panel':
    case 'sunglasses_lens':
    case 'goggles_lens':
    case 'visor':
      return 'curved_lens_panel'
    case 'ergonomic_shell':
    case 'mouse_shell':
    case 'smooth_shell':
    case 'organic_shell':
      return 'ergonomic_shell'
    case 'aircraft_fuselage':
    case 'fuselage':
    case 'fuselage_tube':
    case 'airliner_fuselage':
    case 'airplane_body':
      return 'aircraft_fuselage'
    case 'streamlined_body':
    case 'streamlined_shell':
    case 'aero_body':
    case 'aerodynamic_body':
    case 'train_nose':
    case 'bullet_train_nose':
      return 'streamlined_body'
    case 'lofted_panel':
    case 'loft_panel':
    case 'lofted_shell':
    case 'sectioned_panel':
    case 'transition_panel':
      return 'lofted_panel'
    case 'aircraft_wing':
    case 'main_wing':
    case 'main_wings':
    case 'wing':
    case 'wings':
    case 'low_mounted_wing':
    case 'low_mounted_wings':
    case 'swept_wing':
    case 'swept_wings':
      return 'aircraft_wing'
    case 'aircraft_engine':
    case 'jet_engine':
    case 'jet_engines':
    case 'engine_nacelle':
    case 'engine_nacelles':
    case 'nacelle':
    case 'nacelles':
    case 'aft_mounted_engine':
    case 'aft_mounted_engines':
      return 'aircraft_engine'
    case 'vertical_stabilizer':
    case 'vertical_stabiliser':
    case 'vertical_fin':
    case 'tail_fin':
    case 'aircraft_vertical_stabilizer':
      return 'aircraft_vertical_stabilizer'
    case 'horizontal_stabilizer':
    case 'horizontal_stabiliser':
    case 'horizontal_tail':
    case 't_tail':
    case 't_tail_stabilizer':
    case 'aircraft_horizontal_stabilizer':
      return 'aircraft_horizontal_stabilizer'
    case 'landing_gear':
    case 'aircraft_landing_gear':
    case 'nose_gear':
    case 'main_gear':
      return 'aircraft_landing_gear'
    case 'pipe':
    case 'pipe_stub':
    case 'pipe_port':
    case 'pipe_nozzle':
    case 'hose_port':
    case 'service_port':
    case 'connector_port':
    case 'nozzle':
      return 'pipe_port'
    case 'inlet':
    case 'inlet_port':
    case 'suction_port':
      return 'inlet_port'
    case 'outlet':
    case 'outlet_port':
    case 'discharge_port':
      return 'outlet_port'
    case 'flange':
    case 'flange_ring':
    case 'mounting_flange':
    case 'pipe_flange':
      return 'flange_ring'
    case 'flanged_nozzle':
    case 'flanged_pipe_nozzle':
    case 'nozzle_with_flange':
    case 'process_nozzle':
      return 'flanged_nozzle'
    case 'manway_lid':
    case 'manway_cover':
    case 'manway_hatch':
    case 'access_lid':
    case 'hatch_cover':
      return 'manway_lid'
    case 'inspection_hatch':
    case 'access_hatch':
    case 'round_hatch':
      return 'inspection_hatch'
    case 'sanitary_nozzle':
    case 'tri_clamp_nozzle':
    case 'hygienic_nozzle':
    case 'short_nozzle':
    case 'feed_stub':
      return 'sanitary_nozzle'
    case 'jacket_shell':
    case 'outer_jacket':
    case 'thermal_jacket':
    case 'cooling_jacket':
    case 'heating_jacket':
      return 'jacket_shell'
    case 'sight_glass':
    case 'sightglass':
    case 'inspection_glass':
    case 'view_glass':
    case 'viewing_glass':
      return 'sight_glass'
    case 'sample_valve':
    case 'sampling_valve':
    case 'sampling_port':
    case 'sample_cock':
      return 'sample_valve'
    case 'instrument_port':
    case 'gauge_port':
    case 'thermowell':
    case 'pressure_gauge':
    case 'temperature_probe':
    case 'sensor_port':
      return 'instrument_port'
    case 'stainless_highlight_panel':
    case 'metal_highlight_panel':
    case 'polished_highlight':
    case 'vertical_highlight':
    case 'stainless_reflection':
      return 'stainless_highlight_panel'
    case 'bolts':
    case 'bolt_pattern':
    case 'bolt_circle':
    case 'screw':
    case 'screws':
    case 'screw_pattern':
    case 'fasteners':
    case 'fastener_pattern':
      return 'bolt_pattern'
    case 'control_box':
    case 'control_panel':
    case 'electrical_box':
      return 'control_box'
    case 'ribbed_motor':
    case 'ribbed_motor_body':
    case 'electric_motor':
    case 'industrial_motor':
      return 'ribbed_motor_body'
    case 'conveyor':
    case 'conveyor_frame':
    case 'belt_conveyor':
      return 'conveyor_frame'
    case 'rollers':
    case 'roller_array':
    case 'conveyor_rollers':
      return 'roller_array'
    case 'support_roller_pair':
    case 'support_roller_station':
    case 'trunnion_roller_pair':
    case 'kiln_support_roller':
      return 'support_roller_pair'
    case 'structural_tower_frame':
    case 'tower_frame':
    case 'steel_tower_frame':
    case 'preheater_tower_frame':
    case 'multi_level_tower_frame':
      return 'structural_tower_frame'
    case 'helical_stair':
    case 'helical_stairs':
    case 'spiral_stair':
    case 'spiral_stairs':
    case 'external_spiral_stair':
    case 'tower_spiral_stair':
    case 'wraparound_stair':
    case 'wraparound_stairs':
    case 'ring_stair':
    case 'annular_stair':
      return 'helical_stair'
    case 'helical_ladder':
    case 'helical_ladders':
    case 'spiral_ladder':
    case 'spiral_ladders':
    case 'spiral_access_ladder':
    case 'spiral_access_stair':
    case 'tower_helical_ladder':
    case 'column_spiral_ladder':
    case 'wraparound_ladder':
      return 'helical_ladder'
    case 'cyclone_separator_unit':
    case 'cyclone_unit':
    case 'preheater_cyclone':
    case 'cyclone_stage':
    case 'cyclone_separator':
      return 'cyclone_separator_unit'
    case 'belt':
    case 'belt_surface':
    case 'conveyor_belt':
      return 'belt_surface'
    case 'storage_tank_shell':
    case 'atmospheric_storage_tank':
    case 'flat_roof_tank':
    case 'floating_roof_tank':
      return 'storage_tank_shell'
    case 'tank':
    case 'vessel':
    case 'cylindrical_tank':
    case 'pressure_vessel':
      return 'cylindrical_tank'
    case 'liquid_volume':
    case 'liquid_level':
    case 'tank_liquid':
    case 'fluid_volume':
      return 'liquid_volume'
    case 'cooling_tower_shell':
    case 'natural_draft_cooling_tower':
    case 'hyperboloid_cooling_tower':
      return 'cooling_tower_shell'
    case 'cooling_tower_rim':
    case 'cooling_tower_opening':
    case 'cooling_tower_top_rim':
      return 'cooling_tower_rim'
    case 'chimney':
    case 'chimney_stack':
    case 'smokestack':
    case 'smoke_stack':
    case 'industrial_chimney':
    case 'flue_stack':
      return 'chimney_stack'
    case 'valve':
    case 'valve_body':
      return 'valve_body'
    case 'handwheel':
    case 'hand_wheel':
    case 'valve_wheel':
      return 'handwheel'
    case 'bicycle_wheels':
    case 'bike_wheels':
    case 'bike_wheelset':
    case 'bicycle_wheelset':
      return 'wheel_set'
    case 'handlebar':
    case 'handlebars':
    case 'bike_handlebar':
    case 'bicycle_handlebar':
    case 'bicycle_handlebars':
      return 'handlebar'
    case 'saddle':
    case 'seat':
    case 'bike_seat':
    case 'bicycle_seat':
      return 'saddle'
    case 'chain':
    case 'chain_loop':
    case 'bike_chain':
    case 'bicycle_chain':
    case 'bicycle_crank':
    case 'bike_crank':
    case 'bicycle_chainring':
    case 'bike_chainring':
    case 'bicycle_pedals':
    case 'bike_pedals':
      return 'chain_loop'
    case 'vehicle_wheels':
    case 'car_wheels':
      return 'wheel_set'
    case 'car_windows':
    case 'windows':
      return 'window_strip'
    case 'gearbox':
    case 'gearbox_body':
    case 'reducer':
    case 'speed_reducer':
      return 'gearbox_body'
    case 'filter':
    case 'filter_vessel':
    case 'pressure_filter':
      return 'filter_vessel'
    case 'heat_exchanger':
    case 'exchanger':
    case 'shell_and_tube':
      return 'heat_exchanger'
    case 'agitator':
    case 'agitator_tank':
    case 'mixing_tank':
    case 'mixer_tank':
      return 'agitator_tank'
    case 'pipe_rack':
    case 'pipe_bridge':
    case 'pipe_corridor':
      return 'pipe_rack'
    case 'platform':
    case 'ladder':
    case 'platform_ladder':
    case 'access_platform':
      return 'platform_ladder'
    case 'desk_top':
    case 'table_top':
    case 'desktop':
    case 'worktop':
      return 'desk_top'
    case 'legs':
    case 'feet':
    case 'support_feet':
    case 'mounting_feet':
    case 'rubber_feet':
    case 'leveling_feet':
    case 'leg_set':
    case 'table_legs':
    case 'desk_legs':
      return 'leg_set'
    case 'drawers':
    case 'drawer_stack':
    case 'drawer_unit':
    case 'drawer_cabinet':
      return 'drawer_stack'
    case 'electrical_cabinet':
    case 'electrical_panel':
    case 'control_cabinet':
    case 'power_cabinet':
    case 'switchgear':
      return 'electrical_cabinet'
    case 'pipe_run':
    case 'straight_pipe':
    case 'pipeline':
    case 'process_pipe':
      return 'pipe_run'
    case 'pipe_elbow':
    case 'elbow':
    case 'pipe_bend':
    case 'bend':
      return 'pipe_elbow'
    case 'cable_tray':
    case 'wire_tray':
    case 'tray':
    case 'cable_ladder':
      return 'cable_tray'
    case 'nameplate':
    case 'name_plate':
    case 'rating_plate':
    case 'serial_plate':
    case 'label_plate':
    case 'data_plate':
      return 'nameplate'
    case 'warning_label':
    case 'warning_sticker':
    case 'label':
      return 'warning_label'
    case 'seam_ring':
    case 'seam':
    case 'joint_ring':
      return 'seam_ring'
    default:
      return null
  }
}

export function normalizedPartKind(part: PartComposePartInput): PartComposeKind | null {
  return normalizePartKind(part.kind ?? part.partType ?? part.type)
}
