import { calculateLevelMiters } from '@pascal-app/core'
import { WALL_GRID_STEP } from '../../tools/wall/wall-drafting'

export { FLOORPLAN_VIEW_ROTATION_DEG } from './floorplan-view-rotation'

export const FALLBACK_VIEW_SIZE = 12
export const FLOORPLAN_PADDING = 2
export const MIN_VIEWPORT_WIDTH_RATIO = 0.08
export const MAX_VIEWPORT_WIDTH_RATIO = 40
export const PANEL_MIN_WIDTH = 420
export const PANEL_MIN_HEIGHT = 320
export const PANEL_DEFAULT_WIDTH = 560
export const PANEL_DEFAULT_HEIGHT = 360
export const PANEL_MARGIN = 16
export const PANEL_DEFAULT_BOTTOM_OFFSET = 96
export const MIN_GRID_SCREEN_SPACING = 12
export const GRID_COORDINATE_PRECISION = 6
export const MAJOR_GRID_STEP = WALL_GRID_STEP * 2
export const FLOORPLAN_MINOR_GRID_STROKE_WIDTH = 0.14
export const FLOORPLAN_MAJOR_GRID_STROKE_WIDTH = 0.26
export const FLOORPLAN_WALL_THICKNESS_SCALE = 1.18
export const FLOORPLAN_MIN_VISIBLE_WALL_THICKNESS = 0.13
export const FLOORPLAN_MAX_EXTRA_THICKNESS = 0.035
export const FLOORPLAN_PANEL_LAYOUT_STORAGE_KEY = 'pascal-editor-floorplan-panel-layout'
export const EMPTY_WALL_MITER_DATA = calculateLevelMiters([])
export const EDITOR_CURSOR = "url('/cursor.svg') 4 2, default"
export const FLOORPLAN_CURSOR_INDICATOR_LINE_HEIGHT = 18
export const FLOORPLAN_CURSOR_BADGE_OFFSET_X = 14
export const FLOORPLAN_CURSOR_BADGE_OFFSET_Y = 14
export const FLOORPLAN_CURSOR_MARKER_CORE_RADIUS_PX = 3
export const FLOORPLAN_CURSOR_MARKER_GLOW_RADIUS_PX = 10
export const FLOORPLAN_DRAFT_ANCHOR_RADIUS_PX = 7
export const FLOORPLAN_ENDPOINT_HANDLE_RADIUS_PX = 7
export const FLOORPLAN_ENDPOINT_HANDLE_SELECTED_RADIUS_PX = 8
export const FLOORPLAN_ENDPOINT_HANDLE_ACTIVE_RADIUS_PX = 9
export const FLOORPLAN_ENDPOINT_HANDLE_DOT_RADIUS_PX = 3
export const FLOORPLAN_ENDPOINT_HANDLE_ACTIVE_DOT_RADIUS_PX = 4
export const FLOORPLAN_CURVE_HANDLE_DOT_RADIUS_PX = 3
export const FLOORPLAN_POLYGON_VERTEX_RADIUS_PX = 6.5
export const FLOORPLAN_POLYGON_VERTEX_ACTIVE_RADIUS_PX = 7.5
export const FLOORPLAN_POLYGON_VERTEX_DOT_RADIUS_PX = 2.5
export const FLOORPLAN_POLYGON_VERTEX_ACTIVE_DOT_RADIUS_PX = 3
export const FLOORPLAN_POLYGON_VERTEX_HIT_RADIUS_PX = 14
export const FLOORPLAN_POLYGON_MIDPOINT_RADIUS_PX = 4
export const FLOORPLAN_POLYGON_MIDPOINT_HOVER_RADIUS_PX = 4.6
export const FLOORPLAN_POLYGON_MIDPOINT_DOT_RADIUS_PX = 1.8
export const FLOORPLAN_POLYGON_EDGE_HIT_STROKE_WIDTH_PX = 30
export const FLOORPLAN_POLYGON_EDGE_HOVER_GLOW_STROKE_WIDTH_PX = 12
export const FLOORPLAN_POLYGON_EDGE_VISIBLE_STROKE_WIDTH_PX = 4
export const FLOORPLAN_MARQUEE_OUTLINE_WIDTH = 0.055
export const FLOORPLAN_MARQUEE_GLOW_WIDTH = 0.14
export const FLOORPLAN_HOVER_TRANSITION = 'opacity 180ms cubic-bezier(0.2, 0, 0, 1)'
export const FLOORPLAN_WALL_HIT_STROKE_WIDTH = 18
export const FLOORPLAN_WALL_STROKE_WIDTH = '1'
export const FLOORPLAN_OPENING_HIT_STROKE_WIDTH = 16
export const noopFloorplanStairHandler = () => {}
export const FLOORPLAN_OPENING_STROKE_WIDTH = 0.05
export const FLOORPLAN_ENDPOINT_HIT_STROKE_WIDTH = 18
export const FLOORPLAN_ENDPOINT_HOVER_GLOW_STROKE_WIDTH = 16
export const FLOORPLAN_ENDPOINT_HOVER_RING_STROKE_WIDTH = 7
export const FLOORPLAN_MARQUEE_DRAG_THRESHOLD_PX = 4
export const FLOORPLAN_ACTION_MENU_HORIZONTAL_PADDING = 60
export const FLOORPLAN_ACTION_MENU_MIN_ANCHOR_Y = 56
export const FLOORPLAN_DEFAULT_WINDOW_LOCAL_Y = 1.5

// Match the guide plane footprint used in the 3D renderer so the 2D overlay aligns.
export const FLOORPLAN_GUIDE_BASE_WIDTH = 10
export const FLOORPLAN_GUIDE_MIN_SCALE = 0.01
export const FLOORPLAN_GUIDE_HANDLE_SIZE = 0.22
export const FLOORPLAN_GUIDE_HANDLE_HIT_RADIUS = 0.3
export const FLOORPLAN_GUIDE_SELECTION_STROKE_WIDTH = 0.05
export const FLOORPLAN_GUIDE_HANDLE_HINT_OFFSET = 72
export const FLOORPLAN_GUIDE_HANDLE_HINT_PADDING_X = 92
export const FLOORPLAN_GUIDE_HANDLE_HINT_PADDING_Y = 48
export const FLOORPLAN_GUIDE_ROTATION_SNAP_DEGREES = 45
export const FLOORPLAN_GUIDE_ROTATION_FINE_SNAP_DEGREES = 1
export const FLOORPLAN_SITE_COLOR = '#10b981'
