import { describe, expect, test } from 'bun:test'
import type { AssemblyIR } from '@pascal-app/core/lib/generated-assembly-ir'
import { reviewAssemblyRealism } from './generated-assembly-realism-gate'
import { compileDsl } from './generated-geometry-dsl-compiler'

const GOOD_CONVEYOR = `
  belt({ id: 'belt', length: 6, width: 0.72 });
  rollerArray({ id: 'rollers', length: 6, width: 0.78, count: 8 });
  boxFrame({ id: 'frame', length: 6, width: 0.92, height: 0.78 });
  guardCover({ id: 'cover', target: 'belt', side: 'top', length: 3.8 });
  motor({ id: 'drive_motor', target: 'belt', side: 'right', position: 'rear' });
  inspectionDoor({ id: 'doors', target: 'cover', side: 'right', count: 2 });
  nameplate({ id: 'nameplate', target: 'cover', side: 'front' });
`

function makePrimitiveConveyor(): AssemblyIR {
  return {
    schemaVersion: 1,
    generator: { sourceHash: 'src', apiVersion: '1.1.0', paramsHash: 'params' },
    parts: Array.from({ length: 6 }, (_, i) => ({
      id: `conveyor.box.${i}`,
      transform: {
        space: 'world' as const,
        position: [i, 0, 0] as [number, number, number],
        rotation: [0, 0, 0, 1] as [number, number, number, number],
        scale: [1, 1, 1] as [number, number, number],
      },
      geometry: {
        kind: 'primitive-recipe' as const,
        recipeId: 'primitive.box',
        params: { length: 1, width: 0.5, height: 0.1 },
      },
      material: {},
      fingerprint: `fp-${i}`,
    })),
    constraints: [],
  }
}

describe('reviewAssemblyRealism', () => {
  test('does not apply industrial rules to non-industrial DSL output', () => {
    const result = compileDsl(
      "part('ball', sphere({ radius: 0.5, color: '#cc0000' })).atWorld([0, 0.5, 0]);",
    )
    expect(result.ok).toBe(true)
    if (!result.ok) return

    const review = reviewAssemblyRealism(result.ir)
    expect(review.applicable).toBe(false)
    expect(review.passed).toBe(true)
  })

  test('passes a semantic guarded conveyor generated by the equipment SDK', () => {
    const result = compileDsl(GOOD_CONVEYOR)
    expect(result.ok).toBe(true)
    if (!result.ok) return

    const review = reviewAssemblyRealism(result.ir, { source: GOOD_CONVEYOR })
    expect(review.applicable).toBe(true)
    expect(review.family).toBe('belt_conveyor')
    expect(review.passed).toBe(true)
    expect(review.evidence.anonymousPrimitiveRatio).toBe(0)
  })

  test('rejects anonymous primitive conveyor-shaped output', () => {
    const review = reviewAssemblyRealism(makePrimitiveConveyor(), {
      source: "part('conveyor.box.0', box({ length: 1, width: 1, height: 1 }))",
    })

    expect(review.applicable).toBe(true)
    expect(review.passed).toBe(false)
    expect(review.issues.some((i) => i.startsWith('realism_missing_required_role'))).toBe(true)
    expect(review.issues.some((i) => i.startsWith('realism_anonymous_primitive_ratio'))).toBe(true)
  })
})
