import {
  DSL_API_VERSION,
  type DSLApiCard,
  type DSLApiCardInput,
} from '../generated-geometry-dsl-contract'

const numberInput = (
  range: [number, number],
  unit: DSLApiCardInput['unit'] = 'm',
): DSLApiCardInput => ({
  type: 'number',
  unit,
  range,
})

const stringInput = (required = false): DSLApiCardInput => ({
  type: 'string',
  ...(required ? { required: true } : {}),
})

const enumInput = (values: string[]): DSLApiCardInput => ({
  type: 'string',
  enum: values,
})

export const EQUIPMENT_DSL_API_CARDS: DSLApiCard[] = [
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.belt',
    category: 'industrial',
    signature: 'belt({ id, length?, width?, thickness?, material?, color? })',
    inputs: {
      id: stringInput(true),
      length: numberInput([0.5, 30]),
      width: numberInput([0.15, 3]),
      thickness: numberInput([0.015, 0.18]),
      material: enumInput(['rubber_belt']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 3 },
    example: "belt({ id: 'belt', length: 6, width: 0.72 });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.rollerArray',
    category: 'industrial',
    signature: 'rollerArray({ id, length?, width?, count?, radius?, material?, color? })',
    inputs: {
      id: stringInput(true),
      length: numberInput([0.5, 30]),
      width: numberInput([0.15, 3]),
      count: { type: 'integer', unit: 'count', range: [2, 64] },
      radius: numberInput([0.015, 0.16]),
      material: enumInput(['stainless_steel']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 8 },
    example: "rollerArray({ id: 'rollers', length: 6, width: 0.78, count: 10 });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.boxFrame',
    category: 'industrial',
    signature: 'boxFrame({ id, length?, width?, height?, railThickness?, legCount?, material? })',
    inputs: {
      id: stringInput(true),
      length: numberInput([0.5, 30]),
      width: numberInput([0.2, 4]),
      height: numberInput([0.2, 4]),
      railThickness: numberInput([0.025, 0.16]),
      legCount: { type: 'integer', unit: 'count', range: [4, 16] },
      material: enumInput(['aluminum_frame', 'painted_steel', 'stainless_steel']),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 14 },
    example: "boxFrame({ id: 'frame', length: 6, width: 0.92, height: 0.78 });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.guardCover',
    category: 'industrial',
    signature:
      'guardCover({ id, target?, side?, length?, width?, height?, clearance?, material?, color? })',
    inputs: {
      id: stringInput(true),
      target: stringInput(),
      side: enumInput(['top', 'left', 'right']),
      length: numberInput([0.3, 30]),
      width: numberInput([0.2, 5]),
      height: numberInput([0.12, 4]),
      clearance: numberInput([0.02, 0.5]),
      material: enumInput(['transparent_polycarbonate', 'wire_mesh', 'yellow_safety']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 13 },
    example: "guardCover({ id: 'cover', target: 'belt', side: 'top', length: 3.8 });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.motor',
    category: 'industrial',
    signature: 'motor({ id, target?, side?, position?, diameter?, length?, material?, color? })',
    inputs: {
      id: stringInput(true),
      target: stringInput(),
      side: enumInput(['left', 'right']),
      position: enumInput(['front', 'rear', 'center']),
      diameter: numberInput([0.12, 1.4]),
      length: numberInput([0.16, 2.4]),
      material: enumInput(['painted_steel', 'cast_iron']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 6 },
    example: "motor({ id: 'drive_motor', target: 'belt', side: 'right', position: 'rear' });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.gearbox',
    category: 'industrial',
    signature:
      'gearbox({ id, target?, side?, position?, length?, width?, height?, material?, color? })',
    inputs: {
      id: stringInput(true),
      target: stringInput(),
      side: enumInput(['left', 'right', 'front', 'back']),
      position: enumInput(['front', 'rear', 'center']),
      length: numberInput([0.16, 2.4]),
      width: numberInput([0.12, 1.8]),
      height: numberInput([0.1, 1.6]),
      material: enumInput(['cast_iron', 'painted_steel']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 11 },
    example: "gearbox({ id: 'gearbox', target: 'belt', side: 'right', position: 'rear' });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.bearingBlock',
    category: 'industrial',
    signature:
      'bearingBlock({ id, target?, side?, position?, width?, height?, depth?, material?, color? })',
    inputs: {
      id: stringInput(true),
      target: stringInput(),
      side: enumInput(['left', 'right']),
      position: enumInput(['front', 'rear', 'center']),
      width: numberInput([0.08, 1.2]),
      height: numberInput([0.06, 1.2]),
      depth: numberInput([0.05, 0.9]),
      material: enumInput(['cast_iron', 'painted_steel']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 6 },
    example:
      "bearingBlock({ id: 'rear_bearing', target: 'belt', side: 'right', position: 'rear' });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.platform',
    category: 'industrial',
    signature:
      'platform({ id, target?, side?, length?, width?, height?, thickness?, legCount?, material?, color? })',
    inputs: {
      id: stringInput(true),
      target: stringInput(),
      side: enumInput(['front', 'back', 'left', 'right']),
      length: numberInput([0.4, 12]),
      width: numberInput([0.35, 3]),
      height: numberInput([0.3, 8]),
      thickness: numberInput([0.018, 0.16]),
      legCount: { type: 'integer', unit: 'count', range: [4, 16] },
      material: enumInput(['wire_mesh', 'painted_steel', 'yellow_safety']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 9 },
    example: "platform({ id: 'service_platform', target: 'skid', side: 'front' });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.ladder',
    category: 'industrial',
    signature: 'ladder({ id, target?, side?, height?, width?, rungCount?, material?, color? })',
    inputs: {
      id: stringInput(true),
      target: stringInput(),
      side: enumInput(['front', 'back', 'left', 'right']),
      height: numberInput([0.8, 12]),
      width: numberInput([0.32, 0.75]),
      rungCount: { type: 'integer', unit: 'count', range: [4, 48] },
      material: enumInput(['yellow_safety', 'painted_steel', 'stainless_steel']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 10 },
    example: "ladder({ id: 'access_ladder', target: 'service_platform', side: 'front' });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.handrail',
    category: 'industrial',
    signature:
      'handrail({ id, target?, side?, length?, width?, height?, postCount?, material?, color? })',
    inputs: {
      id: stringInput(true),
      target: stringInput(),
      side: enumInput(['front', 'back', 'left', 'right', 'all']),
      length: numberInput([0.4, 16]),
      width: numberInput([0.3, 6]),
      height: numberInput([0.8, 1.3]),
      postCount: { type: 'integer', unit: 'count', range: [2, 24] },
      material: enumInput(['yellow_safety', 'painted_steel', 'stainless_steel']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 7 },
    example: "handrail({ id: 'platform_rail', target: 'service_platform', side: 'all' });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.inspectionDoor',
    category: 'industrial',
    signature: 'inspectionDoor({ id, target?, side?, count?, width?, height?, material?, color? })',
    inputs: {
      id: stringInput(true),
      target: stringInput(),
      side: enumInput(['left', 'right', 'front', 'back']),
      count: { type: 'integer', unit: 'count', range: [1, 8] },
      width: numberInput([0.15, 2]),
      height: numberInput([0.12, 2]),
      material: enumInput(['painted_steel', 'stainless_steel']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 3 },
    example: "inspectionDoor({ id: 'doors', target: 'cover', side: 'right', count: 2 });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.nameplate',
    category: 'industrial',
    signature: 'nameplate({ id, target?, side?, width?, height?, text? })',
    inputs: {
      id: stringInput(true),
      target: stringInput(),
      side: enumInput(['front', 'back', 'left', 'right']),
      width: numberInput([0.08, 1]),
      height: numberInput([0.04, 0.5]),
      text: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 1 },
    example: "nameplate({ id: 'nameplate', target: 'cover', side: 'front' });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.sheetCover',
    category: 'industrial',
    signature:
      'sheetCover({ id, target?, side?, length?, width?, height?, thickness?, clearance?, material?, color? })',
    inputs: {
      id: stringInput(true),
      target: stringInput(),
      side: enumInput(['top', 'front', 'back', 'left', 'right']),
      length: numberInput([0.12, 12]),
      width: numberInput([0.08, 6]),
      height: numberInput([0.08, 5]),
      thickness: numberInput([0.004, 0.08]),
      clearance: numberInput([0.005, 0.35]),
      material: enumInput(['painted_steel', 'stainless_steel', 'yellow_safety']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 3 },
    example: "sheetCover({ id: 'pump_cover', target: 'motor', side: 'top' });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.flangePort',
    category: 'industrial',
    signature: 'flangePort({ id, target?, side?, nominalDiameter?, length?, material?, color? })',
    inputs: {
      id: stringInput(true),
      target: stringInput(),
      side: enumInput(['front', 'back', 'left', 'right', 'top']),
      nominalDiameter: numberInput([0.04, 1.4]),
      length: numberInput([0.04, 1.2]),
      material: enumInput(['stainless_steel', 'cast_iron']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 2 },
    example: "flangePort({ id: 'inlet', target: 'cabinet', side: 'front', nominalDiameter: 0.2 });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.pipeRun',
    category: 'industrial',
    signature: 'pipeRun({ id, from?, to?, radius?, includeFlanges?, material?, color? })',
    inputs: {
      id: stringInput(true),
      radius: numberInput([0.015, 0.45]),
      includeFlanges: { type: 'boolean' },
      material: enumInput(['stainless_steel', 'painted_steel']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 3 },
    example: "pipeRun({ id: 'process_pipe', from: [-1, 1, 0], to: [1, 1, 0], radius: 0.06 });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.controlCabinet',
    category: 'industrial',
    signature: 'controlCabinet({ id, target?, side?, width?, height?, depth?, material?, color? })',
    inputs: {
      id: stringInput(true),
      target: stringInput(),
      side: enumInput(['left', 'right', 'front', 'back']),
      width: numberInput([0.25, 2.4]),
      height: numberInput([0.45, 3]),
      depth: numberInput([0.12, 1.2]),
      material: enumInput(['painted_steel', 'stainless_steel']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 5 },
    example: "controlCabinet({ id: 'control_cabinet', target: 'frame', side: 'right' });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.skidBase',
    category: 'industrial',
    signature: 'skidBase({ id, length?, width?, height?, railThickness?, material?, color? })',
    inputs: {
      id: stringInput(true),
      length: numberInput([0.6, 8]),
      width: numberInput([0.25, 3]),
      height: numberInput([0.06, 0.8]),
      railThickness: numberInput([0.025, 0.18]),
      material: enumInput(['painted_steel', 'stainless_steel']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 4 },
    example: "skidBase({ id: 'skid', length: 2.4, width: 0.9 });",
  },
  {
    apiVersion: DSL_API_VERSION,
    kind: 'geometry_api_card',
    id: 'industrial.pumpCasing',
    category: 'industrial',
    signature: 'pumpCasing({ id, target?, diameter?, width?, material?, color? })',
    inputs: {
      id: stringInput(true),
      target: stringInput(),
      diameter: numberInput([0.16, 2]),
      width: numberInput([0.08, 0.9]),
      material: enumInput(['painted_steel', 'cast_iron', 'stainless_steel']),
      color: stringInput(),
    },
    outputs: 'PartBuilder[]',
    cost: { parts: 4 },
    example: "pumpCasing({ id: 'pump', target: 'skid', diameter: 0.52 });",
  },
]

export function formatEquipmentDslApiCards(cards = EQUIPMENT_DSL_API_CARDS): string {
  return cards
    .map((card) => {
      const example = card.example.replace(/\s+/g, ' ').trim()
      const cost = card.cost.parts ? ` ~${card.cost.parts} parts` : ''
      return `  ${card.signature} — ${card.id};${cost}; example: ${example}`
    })
    .join('\n')
}
